;;; emacs.el --- Headless editor integration checks -*- lexical-binding: t; -*-
(require 'ert)
(require 'bork-mode)
(require 'eglot)
(require 'flymake)

(ert-deftest bork-lexical-highlighting-and-indent ()
  (with-temp-buffer
    (insert "fn main() {\nprintln(true)\n}\n")
    (bork-mode)
    (font-lock-ensure)
    (should (eq (get-text-property 1 'face) 'font-lock-keyword-face))
    (goto-char (point-min))
    (forward-line 1)
    (bork-indent-line)
    (should (= (current-indentation) 2))))

(ert-deftest bork-positional-variant-highlighting ()
  (with-temp-buffer
    (insert "type Reply[T] = sealed { Found(T, String), Gone }\nmatch(x) { Reply[Int].Found(n, _) => n, .Gone => 0 }\n")
    (bork-mode)
    (font-lock-ensure)
    (goto-char (point-min))
    (while (search-forward "Found" nil t)
      (should (eq (get-text-property (- (point) 5) 'face) 'font-lock-type-face)))))

(ert-deftest bork-tag-group-highlighting ()
  (with-temp-buffer
    (insert "type Row = { value: Int codec { name: \"v\" } }\n")
    (bork-mode)
    (font-lock-ensure)
    (goto-char (point-min))
    (search-forward "codec")
    (should (eq (get-text-property (- (point) 5) 'face) 'font-lock-preprocessor-face))))

(ert-deftest bork-shebang ()
  (with-temp-buffer
    (insert "#!/usr/bin/env -S bork script\nprintln(1)\n")
    (set-auto-mode)
    (should (eq major-mode 'bork-mode))))

(ert-deftest bork-tree-sitter ()
  (let ((treesit-extra-load-path (list (getenv "BORK_TEST_EMACS_PARSER"))))
    (with-temp-buffer
      (insert "type User = { name: String }\nfn main() { println(true) }\n")
      (bork-ts-mode)
      (font-lock-ensure)
      (should (equal (treesit-node-type (treesit-buffer-root-node 'bork)) "source_file"))
      (should (eq (get-text-property 1 'face) 'font-lock-keyword-face))
      (erase-buffer)
      (insert "fn main() {\nreturn\nbreak\ncontinue\n}\n")
      (font-lock-ensure)
      (goto-char (point-min))
      (dolist (keyword '("return" "break" "continue"))
        (search-forward keyword)
        (should (eq (get-text-property (- (point) (length keyword)) 'face)
                    'font-lock-keyword-face))))))

(ert-deftest bork-font-lock-all-repository-files ()
  (dolist (directory '("examples" "testdata/cases"))
    (dolist (file (directory-files-recursively directory "\\.bork\\'"))
      (with-temp-buffer
        (insert-file-contents file)
        (dolist (mode '(bork-mode bork-ts-mode))
          (let ((treesit-extra-load-path (list (getenv "BORK_TEST_EMACS_PARSER"))))
            (funcall mode)
            (font-lock-ensure)))))))

(defun bork-test-wait (predicate)
  (let ((deadline (+ (float-time) 15)))
    (while (and (not (funcall predicate)) (< (float-time) deadline))
      (accept-process-output nil 0.05))
    (should (funcall predicate))))

(defun bork-test-eglot (mode)
  (let* ((directory (make-temp-file "bork-eglot-" t))
         (file (expand-file-name "main.bork" directory))
         (exec-path (cons (file-name-directory (getenv "BORK_TEST_BINARY")) exec-path))
         (treesit-extra-load-path (list (getenv "BORK_TEST_EMACS_PARSER")))
         (eglot-sync-connect 10)
         (eglot-autoshutdown t)
         buffer)
    (unwind-protect
        (progn
          (with-temp-file (expand-file-name "bork.mod" directory)
            (insert "module example.com/editor-test\n"))
          (with-temp-file file (insert "fn main(){println(missing)}\n"))
          (setq buffer (find-file-noselect file))
          (with-current-buffer buffer
            (funcall mode)
            (call-interactively #'eglot)
            (bork-test-wait (lambda () (eglot-managed-p)))
            (should (equal (plist-get (eglot--TextDocumentItem) :languageId) "bork"))
            (flymake-mode 1)
            (flymake-start)
            (bork-test-wait (lambda () (flymake-diagnostics)))
            (let ((before (buffer-string)))
              (eglot-format-buffer)
              (should-not (equal before (buffer-string))))))
      (when (buffer-live-p buffer)
        (with-current-buffer buffer
          (when (eglot-current-server) (eglot-shutdown (eglot-current-server)))
          (set-buffer-modified-p nil))
        (kill-buffer buffer))
      (delete-directory directory t))))

(ert-deftest bork-eglot-attach-diagnostics-and-format ()
  (bork-test-eglot 'bork-mode))
(ert-deftest bork-ts-eglot-attach-diagnostics-and-format ()
  (bork-test-eglot 'bork-ts-mode))

(ert-run-tests-batch-and-exit)
