/// <reference types="tree-sitter-cli/dsl" />
const comma = rule => seq(rule, repeat(seq(',', rule)), optional(','));
const items = (rule, $) => repeat(seq(rule, optional(choice(',', ';', $._newline))));
module.exports = grammar({
  name: 'bork',
  extras: $ => [/\s/, $.comment],
  word: $ => $.identifier,
  externals: $ => [$.go_content, $._newline, $._error_sentinel],
  conflicts: $ => [
    [$.record_expression, $.map_literal],
    [$.generic_expression, $.call_expression, $.record_expression, $.binary_expression],
    [$.generic_expression, $.call_expression, $.record_expression, $.lambda_expression],
    [$.binding, $.record_expression],
    [$.trust_statement, $.record_expression],
    [$.generic_expression, $.call_expression, $.record_expression, $.unary_expression],
    [$.record_expression, $.list_literal],
    [$._statement, $.record_expression],
    [$.scope_expression, $.record_expression],
    [$.type],
    [$.qualified_name, $.binding],
    [$.qualified_name, $.lambda_parameter],
    [$.qualified_name],
    [$._expression, $.scope_expression],
    [$.type_declaration],
    [$.use_declaration],
    [$.block, $.record_literal],
    [$.type, $._expression],
  ],
  rules: {
    source_file: $ => seq(optional($.shebang), repeat(choice($._declaration, $._statement, ';', $._newline))),
    shebang: _ => token(seq('#!', /[^\n]*/)),
    comment: _ => token(choice(seq('//', /[^\n]*/), seq('/*', /[^*]*\*+([^/*][^*]*\*+)*/, '/'))),
    identifier: _ => /[\p{L}][\p{L}\p{N}_]*/u,
    _declaration: $ => choice($.import_declaration, $.use_declaration, $.type_declaration, $.function_declaration, $.predicate_declaration, $.rule_declaration, $.test_declaration, $.class_declaration, $.instance_declaration, $.instances_declaration, $.providers_declaration, $.ambient_declaration),
    import_declaration: $ => seq('import', optional($.identifier), $.string),
    use_declaration: $ => seq('use', $.qualified_name, optional(seq('.', '*'))),
    qualified_name: $ => prec.dynamic(1,  seq($.identifier, repeat(seq('.', $.identifier)))),
    type_declaration: $ => seq('type', field('name', $.identifier), optional($.type_parameters), '=', choice(seq(optional('private'), $.record_type, optional($.where_clause)), seq('sealed', '{', items($.variant, $), '}', optional($.where_clause)), seq('resource', optional($.go_type)), seq($.go_type, optional($.record_type), optional($.where_clause)), $.type), optional($.derive_clause)),
    go_type: $ => seq('go', $.string),
    derive_clause: $ => seq('derive', '(', comma($.qualified_name), ')'),
    record_type: $ => seq('{', items($.field_declaration, $), '}'),
    field_declaration: $ => seq(optional('lazy'), field('name', $.identifier), ':', $.type, optional(seq('=', $._expression)), optional($.go_tags)),
    go_tags: $ => seq('go', '{', items(seq($.identifier, ':', $.string), $), '}'),
    variant: $ => seq(field('name', $.identifier), optional($.record_type), optional($.where_clause)),
    type_parameters: $ => seq('[', comma(seq($.identifier, optional(seq(':', $.qualified_name, repeat(seq('+', $.qualified_name)))))), ']'),
    function_declaration: $ => seq('fn', optional($.receiver), field('name', $.identifier), choice(seq('=', $.qualified_name), seq(optional($.type_parameters), $.parameters, optional($.where_clause), optional($.uses_clause), optional($.needs_clause), optional(seq(':', $.type)), choice($.block, $.go_body)))),
    receiver: $ => seq('(', $.identifier, ':', $.type, ')'),
    parameters: $ => seq('(', optional(comma($.parameter)), ')'),
    parameter: $ => seq(field('name', $.identifier), ':', $.type, optional(seq('in', $.identifier)), optional(seq('=', $._expression))),
    uses_clause: $ => seq('uses', $.identifier, repeat(seq('+', $.identifier))),
    needs_clause: $ => seq('needs', $.qualified_name, optional('?'), repeat(seq('+', $.qualified_name, optional('?')))),
    where_clause: $ => prec.right(seq('where', $.requirement, repeat(seq(choice('and', 'or'), $.requirement)))),
    requirement: $ => choice($.qualified_name, $.number, $.string, $.rune, $.boolean, seq('(', $.requirement, ')'), prec(10, seq($.qualified_name, optional($.type_arguments), '(', optional(comma($._expression)), ')')), prec(9, seq(choice('-', '!'), $.requirement)), ...['<', '<=', '>', '>=', '==', '!=', '+', '-', '*', '/', '%', 'and', 'or', '||', '&&'].map(op => prec.left(1, seq($.requirement, op, $.requirement)))),
    type: $ => prec.dynamic(1, seq(choice($.qualified_name, seq('(', comma($.type), ')'), $.function_type), optional($.type_arguments), optional($.uses_clause), optional($.where_clause), repeat(seq('|', $.type)))),
    type_arguments: $ => seq('[', comma($.type), ']'),
    function_type: $ => prec(1, seq('(', optional(comma($.type)), ')', optional($.uses_clause), '=>', $.type)),
    predicate_declaration: $ => seq('pred', field('name', $.identifier), optional($.type_parameters), $.parameters, optional($.uses_clause), optional($.needs_clause), choice($.block, $.go_body)),
    rule_declaration: $ => seq('rule', field('name', $.identifier), $.parameters, '{', $.requirement, '=>', $.requirement, '}'),
    test_declaration: $ => seq('test', $.string, optional($.parameters), $.block),
    class_declaration: $ => seq('class', field('name', $.identifier), $.type_parameters, '{', repeat($.method_signature), '}'),
    method_signature: $ => seq('fn', field('name', $.identifier), optional($.type_parameters), $.parameters, optional($.where_clause), optional($.uses_clause), optional($.needs_clause), optional(seq(':', $.type))),
    instance_declaration: $ => seq('instance', field('name', $.identifier), optional($.type_parameters), ':', $.type, '{', repeat($.function_declaration), '}'),
    instances_declaration: $ => seq('instances', $.identifier, '{', items(seq($.qualified_name, optional(seq('.', '*'))), $), '}'),
    providers_declaration: $ => seq('providers', $.identifier, '=', '{', items(seq($.identifier, ':', $.qualified_name), $), '}'),
    ambient_declaration: $ => seq(repeat(choice('logged', seq('propagated', '(', $.string, ')'))), 'ambient', $.identifier, ':', $.type),
    _statement: $ => choice($.binding, $.trust_statement, $._expression),
    binding: $ => seq(optional(choice('lazy', seq('async', '(', $._expression, ')'))), field('name', choice($.identifier, alias('lazy', $.identifier), '_')), optional(seq(':', $.type)), '=', $._expression),
    trust_statement: $ => seq('trust', $._expression),
    block: $ => seq('{', items($._statement, $), '}'),
    _expression: $ => choice($.generic_expression, $.qualified_name, $.number, $.string, $.rune, $.boolean, $.interpolated_string, $.block, $.record_expression, $.list_literal, $.map_literal, $.parenthesized_expression, $.call_expression, $.selector_expression, $.try_expression, $.unary_expression, $.binary_expression, $.lambda_expression, $.if_expression, $.match_expression, $.return_expression, $.scope_expression, $.with_expression, $.generate_expression, $.yield_expression, $.for_expression, $.comptime_expression, $.mock_expression, 'break', 'continue', $.go_body),
    number: _ => token(choice(/0[xX][\da-fA-F_]+/, /0[bB][01_]+/, /0[oO][0-7_]+/, /\d[\d_]*(\.\d[\d_]*)?([eE][+-]?[\d_]+)?/)),
    string: $ => seq('"', repeat(choice($.escape_sequence, token.immediate(prec(1, /[^"\\]+/)))), token.immediate('"')),
    escape_sequence: _ => token.immediate(seq('\\', /./)),
    rune: _ => token(seq("'", choice(/[^'\\]/, /\\([^xuU]|x[\da-fA-F]{2}|u[\da-fA-F]{4}|U[\da-fA-F]{8})/), "'")),
    boolean: _ => choice('true', 'false'),
    interpolated_string: $ => prec(2, seq(field('prefix', $.qualified_name), token.immediate('"'), repeat(choice($.escape_sequence, token.immediate(prec(1, /[^"\\$]+/)), token.immediate('$$'), $.interpolation)), token.immediate('"'))),
    interpolation: $ => choice(seq(token.immediate('${'), $._expression, '}'), seq(token.immediate('$'), alias(token.immediate(/[\p{L}][\p{L}\p{N}_]*/u), $.identifier))),
    parenthesized_expression: $ => seq('(', $._expression, ')'),
    generic_expression: $ => prec.left(14, seq($._expression, $.type_arguments)),
    call_expression: $ => prec.left(14, seq(field('function', $._expression), optional($.type_arguments), '(', optional(comma($.argument)), ')')),
    argument: $ => seq(optional(seq(choice($._expression, alias('scope', $.identifier)), ':')), $._expression),
    selector_expression: $ => prec.left(15, seq(optional($._expression), '.', field('field', $.identifier), optional($.type_arguments))),
    try_expression: $ => prec.left(13, seq($._expression, '?')),
    record_expression: $ => prec.dynamic(1, seq(choice($._expression, '.'), optional($.type_arguments), $.record_literal)),
    record_literal: $ => seq('{', items(seq(field('name', $.identifier), ':', $._expression), $), '}'),
    list_literal: $ => seq('[', items($._expression, $), ']'),
    map_literal: $ => seq('{', choice(':', repeat1(seq($._expression, ':', $._expression, optional(',')))), '}'),
    unary_expression: $ => prec(11, seq(choice('-', '!'), $._expression)),
    binary_expression: $ => choice(...[['|>',1], ['||',2], ['&&',3], ['==',4], ['!=',4], ['<',4], ['<=',4], ['>',4], ['>=',4], ['+',5], ['-',5], ['*',6], ['/',6], ['%',6]].map(([op,p]) => prec.left(p, seq(field('left',$._expression), field('operator',op), field('right',$._expression))))),
    lambda_expression: $ => prec.right(1, seq(choice($.identifier, seq('(', optional(comma($.lambda_parameter)), ')')), '=>', $._expression)),
    lambda_parameter: $ => seq($.identifier, optional(seq(':', $.type))),
    if_expression: $ => seq('if', '(', $._expression, ')', $.block, optional(seq('else', choice($.if_expression, $.block)))),
    match_expression: $ => seq('match', '(', $._expression, ')', '{', items($.match_arm, $), '}'),
    match_arm: $ => seq($.pattern, '=>', $._expression),
    pattern: $ => choice('_', $.number, seq('-', $.number), $.string, $.rune, $.boolean, seq($.identifier, ':', $.type), seq($.qualified_name, optional(seq('{', items(seq($.identifier, optional(seq(':', $.pattern))), $), '}'))), seq('[', items(choice($.pattern, seq('...', optional($.identifier))), $), ']')),
    return_expression: $ => prec.right(seq('return', optional($._expression))),
    scope_expression: $ => prec.dynamic(2, seq('scope', $.identifier, optional(seq('with', comma($._expression))), $.block)),
    with_expression: $ => seq('with', '(', items(seq($.qualified_name, ':', $._expression), $), ')', $.block),
    generate_expression: $ => seq('generate', $.type_arguments, $.block),
    yield_expression: $ => prec.right(seq('yield', $._expression)),
    for_expression: $ => seq('for', '(', $.identifier, 'in', $._expression, ')', $.block),
    comptime_expression: $ => seq('comptime', $.block),
    mock_expression: $ => seq('mock', $.qualified_name, '(', optional(comma(choice($.identifier, '_'))), ')', $.block),
    go_body: $ => seq('unsafe', 'go', choice($.string, seq('{', optional($.go_content), '}'))),
  },
});
