/// <reference types="tree-sitter-cli/dsl" />
const comma = rule => seq(rule, repeat(seq(',', rule)), optional(','));
const bindings = rule => seq(rule, repeat(seq(',', rule)));
const tuple = rule => seq('(', rule, ',', optional(comma(rule)), ')');
const semis = $ => choice(';', $._newline);
// Match parser.list(): semicolons may repeat, but each comma follows an item.
const items = (rule, $, required = false, leading = semis($)) => {
  const terminated = seq(rule, choice(seq(',', repeat(semis($))), repeat1(semis($))));
  return seq(repeat(leading), required
    ? choice(seq(repeat1(terminated), optional(rule)), rule)
    : seq(repeat(terminated), optional(rule)));
};
// Blocks require a semicolon or newline between statements, never a comma.
const statements = (rule, $) => seq(repeat(semis($)), repeat(seq(
  rule, repeat1(semis($)),
)), optional(rule));
module.exports = grammar({
  name: 'bork',
  extras: $ => [/\s/, $.comment],
  word: $ => $.identifier,
  externals: $ => [$.go_content, $._newline, $._error_sentinel, $.bare_return, $.bare_break, $.bare_continue, $._tag_group_start, $._comment_content],
  conflicts: $ => [
    [$.pattern, $._iteration_binding],
    [$.qualified_name, $._iteration_binding],
    [$.qualified_name, $.binding, $.pattern],
    [$.selector_expression, $.context_pattern],
    [$.parenthesized_expression, $.list_comprehension],
    [$.list_comprehension, $._for_header],
    [$.parenthesized_expression, $._for_header],
    [$._head_expression, $.for_expression],
    [$.type, $.specialized_variant_pattern],
    [$._expression, $.specialized_variant_pattern],
    [$._expression, $.pattern, $.specialized_variant_pattern],
    [$._expression, $.pattern],
    [$.list_literal, $.pattern],
    [$.tuple_type],
    [$.type, $._pattern_type],
    [$._pattern_type],
    [$._pattern_type, $._pattern_function_type],
    [$.tuple_type, $._pattern_function_type],
    [$.field_declaration],
    [$.variant],
    [$._identifier, $.go_type],
    [$._identifier, $.type_declaration],
    [$._identifier, $.derive_declaration],
    [$._identifier, $.derive_template_declaration, $.derive_declaration],
    [$._identifier, $.derive_helper_declaration],
    [$._identifier, $.argument],
    [$._identifier, $.mock_expression],
    [$._identifier, $.binding],
    [$._identifier, $.comptime_expression],
    [$._identifier, $.comptime_control_expression],
    [$._identifier, $.list_comprehension, $.comptime_control_expression],
    [$._identifier, $.ambient_declaration],
    [$._identifier, $.with_expression],
    [$._identifier, $.scope_expression],
    [$._identifier, $.select_expression],
    [$._identifier, $.instances_declaration],
    [$._identifier, $.test_declaration],
    [$._identifier, $.instance_declaration],
    [$._identifier, $.class_declaration],
    [$._identifier, $.use_declaration],
    [$._identifier, $.import_declaration],
    [$.record_expression, $.map_literal],
    [$.generic_expression, $.call_expression, $.record_expression, $.binary_expression],
    [$.generic_expression, $.call_expression, $.record_expression, $.lambda_expression],
    [$.binding, $.record_expression],
    [$.trust_statement, $.record_expression],
    [$.generic_expression, $.call_expression, $.record_expression, $.unary_expression],
    [$.record_expression, $.list_literal],
    [$._statement, $.record_expression],
    [$.scope_expression, $.record_expression],
    [$.qualified_name, $.test_pattern],
    [$.tuple_type, $.test_tuple_pattern],
    [$.type, $.test_pattern],
    [$.record_expression, $.select_arm],
    [$.type],
    [$.qualified_name, $.binding],
    [$.qualified_name, $.lambda_parameter],
    [$.qualified_name],
    [$._expression, $.scope_expression],
    [$._expression, $.for_expression],
    [$._expression, $.if_expression],
    [$.type_declaration],
    [$.use_declaration],
    [$.block, $.record_literal],
    [$.block, $.map_literal],
    [$.type, $._expression],
  ],
  rules: {
    source_file: $ => seq(optional($.shebang), repeat(choice($._declaration, $._statement, ';', $._newline))),
    shebang: _ => token(seq('#!', /[^\n]*/)),
    comment: $ => choice(token(choice(seq('//', /[^\n]*/), seq('/*', /[^*]*\*+([^/*][^*]*\*+)*/, '/'))), $._comment_content),
    _identifier: $ => choice($.identifier, ...['is', 'import', 'use', 'class', 'instance', 'test', 'instances', 'scope', 'with', 'resource', 'private', 'derive', 'uses', 'nothing', 'in', 'ambient', 'logged', 'propagated', 'needs', 'comptime', 'lazy', 'async', 'mock', 'go', 'select', 'metadata'].map(word => alias(word, $.identifier))),
    identifier: _ => /[\p{L}][\p{L}\p{N}_]*/u,
    _declaration: $ => prec.dynamic(10, choice($.import_declaration, $.use_declaration, $.type_declaration, $.derive_declaration, $.derive_template_declaration, $.derive_helper_declaration, $.function_declaration, $.predicate_declaration, $.rule_declaration, $.test_declaration, $.class_declaration, $.instance_declaration, $.instances_declaration, $.ambient_declaration)),
    import_declaration: $ => prec.dynamic(10, seq('import', optional($._identifier), $.string)),
    use_declaration: $ => prec.dynamic(10, seq('use', $.qualified_name, optional(seq('.', '*')))),
    qualified_name: $ => prec.dynamic(1,  seq($._identifier, repeat(seq('.', $._identifier)))),
    type_declaration: $ => seq(optional(prec.dynamic(20, 'metadata')), 'type', field('name', $._identifier), optional($.type_parameters), '=', choice(seq(optional('private'), $.record_type, repeat($.tag_group), optional($.where_clause)), seq('sealed', '{', items($.variant, $), '}', repeat($.tag_group), optional($.where_clause)), seq('resource', optional($.go_type), repeat($.tag_group)), seq($.go_type, optional($.record_type), repeat($.tag_group), optional($.where_clause)), seq($.type, repeat($.tag_group))), optional($.derive_clause)),
    go_type: $ => seq('go', $.string),
    derive_template_declaration: $ => prec.dynamic(10, seq('derive', $.instance_declaration)),
    derive_helper_declaration: $ => prec.dynamic(10, seq('derive', $.function_declaration)),
    derive_declaration: $ => prec.dynamic(10, seq('derive', field('class', $.qualified_name), 'for', field('target', $.type))),
    derive_clause: $ => prec.dynamic(10, seq('derive', '(', comma($.qualified_name), ')')),
    record_type: $ => seq('{', items($.field_declaration, $), '}'),
    field_declaration: $ => seq(optional('lazy'), field('name', $._identifier), ':', $.type, optional(seq('=', $._expression)), repeat($.tag_group)),
    tag_group: $ => prec.dynamic(10, seq(field('package', alias($._tag_group_start, $.identifier)), '{', items($.tag_entry, $), '}')),
    tag_entry: $ => seq(field('name', $._identifier), ':', $._expression),
    variant: $ => seq(field('name', $._identifier), optional(choice($.record_type, seq('(', comma($.type), ')'))), repeat($.tag_group), optional($.where_clause)),
    type_parameters: $ => seq('[', comma(seq($._identifier, optional(seq(':', $.qualified_name, repeat(seq('+', $.qualified_name)))))), ']'),
    function_declaration: $ => seq('fn', optional($.receiver), field('name', $._identifier), choice(seq('=', $.qualified_name), seq(optional($.type_parameters), $.parameters, optional($.where_clause), optional($.uses_clause), optional($.needs_clause), optional(seq(':', $.type)), choice($.block, $.go_body)))),
    receiver: $ => seq('(', field('name', $._identifier), ':', $.type, ')'),
    parameters: $ => seq('(', optional(comma($.parameter)), ')'),
    parameter: $ => seq(field('name', $._identifier), ':', $.type, optional(seq('in', $._identifier)), optional(seq('=', $._expression))),
    uses_clause: $ => prec.right(seq('uses', $._identifier, repeat(seq('+', $._identifier)))),
    needs_clause: $ => seq('needs', $.qualified_name, optional('?'), repeat(seq('+', $.qualified_name, optional('?')))),
    where_clause: $ => prec.right(seq('where', $.requirement, repeat(seq(choice('and', 'or'), $.requirement)))),
    requirement: $ => choice($.qualified_name, $.number, $.string, $.rune, $.boolean, $.list_literal,
      seq('(', $.requirement, ')'),
      prec.left(14, seq($.requirement, optional($.type_arguments), '(', optional(comma($._expression)), ')')),
      prec.left(15, seq($.requirement, '.', $._identifier)),
      prec(11, seq(choice('-', '!', '^'), $.requirement)),
      ...[['or',1], ['and',2], ['||',3], ['&&',4], ['==',5], ['!=',5], ['<',5], ['<=',5], ['>',5], ['>=',5], ['+',6], ['-',6], ['|',6], ['^',6], ['&',7], ['<<',7], ['>>',7], ['*',7], ['/',7], ['%',7]].map(([op,p]) => prec.left(p, seq($.requirement, op, $.requirement)))),
    type: $ => prec.dynamic(1, seq(choice($.qualified_name, seq('(', $.type, ')'), $.tuple_type, $.function_type), optional($.type_arguments), optional($.uses_clause), optional($.where_clause), repeat(seq('|', $.type)))),
    type_arguments: $ => seq('[', comma($.type), ']'),
    tuple_type: $ => tuple($.type),
    function_type: $ => prec(1, seq('(', optional(comma($.type)), ')', optional($.uses_clause), '=>', $.type)),
    predicate_declaration: $ => seq('pred', field('name', $._identifier), optional($.type_parameters), $.parameters, optional($.uses_clause), optional($.needs_clause), choice($.block, $.go_body)),
    rule_declaration: $ => seq('rule', field('name', $._identifier), $.parameters, '{', $.requirement, '=>', $.requirement, '}'),
    test_declaration: $ => prec.dynamic(10, seq('test', $.string, optional($.parameters), $.block)),
    class_declaration: $ => prec.dynamic(10, seq('class', field('name', $._identifier), $.type_parameters, '{', repeat(choice($.method_signature, ';', $._newline)), '}')),
    method_signature: $ => seq('fn', field('name', $._identifier), optional($.type_parameters), $.parameters, optional($.where_clause), optional($.uses_clause), optional($.needs_clause), optional(seq(':', $.type))),
    instance_declaration: $ => prec.dynamic(10, seq('instance', field('name', $._identifier), optional($.type_parameters), ':', $.type, '{', repeat(choice($.function_declaration, $.instance_metadata, ';', $._newline)), '}')),
    instance_metadata: $ => seq('metadata', $.type, '=', $._expression),
    instances_declaration: $ => prec.dynamic(10, seq('instances', $._identifier, '{', items(seq($.qualified_name, optional(seq('.', '*'))), $), '}')),
    ambient_declaration: $ => prec.dynamic(10, seq(repeat(choice('logged', seq('propagated', '(', $.string, ')'))), 'ambient', $._identifier, ':', $.type)),
    _statement: $ => choice($.bare_return, $.bare_break, $.bare_continue, $.binding, $.trust_statement, $._expression),
    binding: $ => seq(optional(choice('lazy', seq('async', '(', $._expression, ')'))), field('name', choice($._identifier, alias('lazy', $.identifier), '_', $.tuple_pattern)), optional(seq(':', $.type)), '=', $._expression),
    trust_statement: $ => seq('trust', $._expression),
    block: $ => seq('{', statements($._statement, $), '}'),
    _expression: $ => choice($.generic_expression, $.qualified_name, $.number, $.string, $.rune, $.boolean, $.interpolated_string, $.block, $.record_expression, $.list_literal, $.map_literal, $.parenthesized_expression, $.tuple_literal, $.call_expression, $.selector_expression, $.try_expression, $.unary_expression, $.binary_expression, $.is_expression, $.lambda_expression, $.if_expression, $.match_expression, $.select_expression, $.return_expression, $.scope_expression, $.with_expression, $.generate_expression, $.yield_expression, $.for_expression, $.comprehension_expression, $.comptime_expression, $.comptime_control_expression, $.mock_expression, 'break', 'continue', $.go_body),
    // A bare Name { in a head begins the body. Delimited operands restore
    // ordinary expression parsing, including record literals.
    _head_expression: $ => choice($.qualified_name, $.number, $.string, $.rune, $.boolean, $.interpolated_string, $.block, $.list_literal, $.map_literal, $.parenthesized_expression, $.tuple_literal, alias($._head_context_record, $.record_expression),
      alias($._head_generic, $.generic_expression), alias($._head_call, $.call_expression), alias($._head_selector, $.selector_expression), alias($._head_try, $.try_expression), alias($._head_unary, $.unary_expression), alias($._head_binary, $.binary_expression), alias($._head_is, $.is_expression), alias($._head_lambda, $.lambda_expression),
      $.if_expression, $.match_expression, $.scope_expression, $.with_expression, $.generate_expression, $.for_expression, $.comptime_expression, $.comptime_control_expression, $.mock_expression, $.go_body, alias($._head_return, $.return_expression), alias($._head_yield, $.yield_expression), 'break', 'continue'),
    _head_context_record: $ => seq('.', $.record_literal),
    _head_return: $ => prec.right(seq('return', optional($._head_expression))),
    _head_yield: $ => prec.right(seq('yield', $._head_expression)),
    _head_generic: $ => prec.left(14, seq($._head_expression, $.type_arguments)),
    _head_call: $ => prec.left(14, seq(field('function', $._head_expression), optional($.type_arguments), '(', optional(comma($.argument)), ')')),
    _head_selector: $ => prec.left(15, seq(optional($._head_expression), '.', field('field', choice($._identifier, $.tuple_index)), optional($.type_arguments))),
    _head_try: $ => prec.left(13, seq($._head_expression, '?')),
    _head_unary: $ => prec(11, seq(choice('-', '!', '^'), $._head_expression)),
    _head_binary: $ => choice(...[['|>',1], ['||',2], ['&&',3], ['==',4], ['!=',4], ['<',4], ['<=',4], ['>',4], ['>=',4], ['+',5], ['-',5], ['|',5], ['^',5], ['&',6], ['<<',6], ['>>',6], ['*',6], ['/',6], ['%',6]].map(([op,p]) => prec.left(p, seq(field('left',$._head_expression), field('operator',op), field('right',$._head_expression))))),
    _head_is: $ => prec.left(4, seq(field('value', $._head_expression), 'is', field('pattern', alias($._head_test_pattern, $.test_pattern)))),
    _head_test_pattern: $ => prec.dynamic(2, prec.right(2, choice($.test_tuple_pattern, $.test_parenthesized_pattern, '_', $.number, seq('-', $.number), $.string, $.rune, $.boolean, seq(field('name', choice($._identifier, '_')), ':', $.type), seq(choice($.type, $.specialized_variant_pattern, $.context_pattern), optional(seq('(', items($.test_pattern, $), ')'))), seq('[', items(choice($.test_pattern, seq('...', optional(field('name', $._identifier)))), $), ']')))),
    _head_lambda: $ => prec.right(1, seq(choice(field('parameter', $._identifier), seq('(', optional(comma($.lambda_parameter)), ')')), '=>', $._head_expression)),
    number: _ => token(choice(/0[xX][\da-fA-F_]+/, /0[bB][01_]+/, /0[oO][0-7_]+/, /\d[\d_]*(\.\d[\d_]*)?([eE][+-]?[\d_]+)?/)),
    string: $ => seq('"', repeat(choice($.escape_sequence, token.immediate(prec(1, /[^"\\]+/)))), token.immediate('"')),
    escape_sequence: _ => token.immediate(seq('\\', /./)),
    rune: _ => token(seq("'", choice(/[^'\\]/, /\\([^xuU]|x[\da-fA-F]{2}|u[\da-fA-F]{4}|U[\da-fA-F]{8})/), "'")),
    boolean: _ => choice('true', 'false'),
    interpolated_string: $ => prec(2, seq(field('prefix', $.qualified_name), token.immediate('"'), repeat(choice($.escape_sequence, token.immediate(prec(1, /[^"\\$]+/)), token.immediate('$$'), $.interpolation)), token.immediate('"'))),
    interpolation: $ => choice(seq(token.immediate('${'), $._expression, '}'), seq(token.immediate('$'), alias(token.immediate(/[\p{L}][\p{L}\p{N}_]*/u), $.identifier))),
    tuple_literal: $ => tuple($._expression),
    tuple_pattern: $ => tuple($.pattern),
    parenthesized_pattern: $ => seq('(', $.pattern, ')'),
    tuple_index: _ => /[0-9]+/,
    parenthesized_expression: $ => seq('(', $._expression, ')'),
    generic_expression: $ => prec.left(14, seq($._expression, $.type_arguments)),
    call_expression: $ => prec.left(14, seq(field('function', $._expression), optional($.type_arguments), '(', optional(comma($.argument)), ')')),
    argument: $ => seq(optional(seq(choice($._expression, alias('scope', $.identifier)), ':')), $._expression),
    selector_expression: $ => prec.left(15, seq(optional($._expression), '.', field('field', choice($._identifier, $.tuple_index)), optional($.type_arguments))),
    try_expression: $ => prec.left(13, seq($._expression, '?')),
    record_expression: $ => prec.dynamic(1, seq(choice($._expression, '.'), optional($.type_arguments), $.record_literal)),
    record_literal: $ => seq('{', items(seq(field('name', $._identifier), ':', $._expression), $), '}'),
    list_literal: $ => seq('[', choice(items($._expression, $), $.list_comprehension), ']'),
    list_comprehension: $ => prec.dynamic(20, seq('comptime', 'for', '(', $._iteration_binding, 'in', $._expression, ')', optional(seq('comptime', 'if', '(', $._expression, ')')), $._expression)),
    map_literal: $ => seq('{', choice(':', items(seq($._expression, ':', $._expression), $, true, $._newline)), '}'),
    unary_expression: $ => prec(11, seq(choice('-', '!', '^'), $._expression)),
    binary_expression: $ => choice(...[['|>',1], ['||',2], ['&&',3], ['==',4], ['!=',4], ['<',4], ['<=',4], ['>',4], ['>=',4], ['+',5], ['-',5], ['|',5], ['^',5], ['&',6], ['<<',6], ['>>',6], ['*',6], ['/',6], ['%',6]].map(([op,p]) => prec.left(p, seq(field('left',$._expression), field('operator',op), field('right',$._expression))))),
    is_expression: $ => prec.left(4, seq(field("value", $._expression), "is", field("pattern", $.test_pattern))),
    lambda_expression: $ => prec.right(1, seq(choice(field('parameter', $._identifier), seq('(', optional(comma($.lambda_parameter)), ')')), '=>', $._expression)),
    lambda_parameter: $ => seq($._identifier, optional(seq(':', $.type))),
    if_expression: $ => seq('if', $._head_expression, $.block, optional(seq('else', choice($.if_expression, $.block)))),
    match_expression: $ => seq('match', $._head_expression, '{', items($.match_arm, $), '}'),
    match_arm: $ => seq($.pattern, '=>', $._expression),
    pattern: $ => prec.right(choice($.tuple_pattern, $.parenthesized_pattern, '_', $.number, seq('-', $.number), $.string, $.rune, $.boolean, seq(field('name', choice($._identifier, '_')), ':', alias($._pattern_type, $.type)), seq(choice($.qualified_name, $.specialized_variant_pattern, $.context_pattern), optional(choice(seq('{', items($.field_pattern, $), '}'), seq('(', items($.pattern, $), ')')))), seq('[', items(choice($.pattern, seq('...', optional(field('name', $._identifier)))), $), ']'))),
    _pattern_type: $ => prec.dynamic(1, seq(choice($.qualified_name, seq('(', $.type, ')'), $.tuple_type, alias($._pattern_function_type, $.function_type)), optional($.type_arguments), optional($.uses_clause), optional($.where_clause), repeat(seq('|', alias($._pattern_type, $.type))))),
    _pattern_function_type: $ => seq('(', optional(comma($.type)), ')', optional($.uses_clause), '=>', alias($._pattern_type, $.type)),
    test_pattern: $ => prec.dynamic(2, prec.right(2, choice($.test_tuple_pattern, $.test_parenthesized_pattern, '_', $.number, seq('-', $.number), $.string, $.rune, $.boolean, seq(field('name', choice($._identifier, '_')), ':', $.type), seq(choice($.type, $.specialized_variant_pattern, $.context_pattern), optional(choice(seq('{', items($.test_field_pattern, $), '}'), seq('(', items($.test_pattern, $), ')')))), seq('[', items(choice($.test_pattern, seq('...', optional(field('name', $._identifier)))), $), ']')))),
    test_tuple_pattern: $ => prec.right(seq(tuple($.test_pattern), optional($.uses_clause), optional(seq('=>', $.type)), optional($.where_clause), repeat(seq('|', $.type)))),
    test_parenthesized_pattern: $ => prec.right(seq('(', $.test_pattern, ')', optional($.uses_clause), optional(seq('=>', $.type)), optional($.where_clause), repeat(seq('|', $.type)))),
    test_field_pattern: $ => seq(field('name', $._identifier), optional(seq(':', field('pattern', $.test_pattern)))),
    specialized_variant_pattern: $ => seq($.qualified_name, $.type_arguments, '.', field('name', $._identifier)),
    context_pattern: $ => prec(15, seq('.', field('name', $._identifier))),
    field_pattern: $ => seq(field('name', $._identifier), optional(seq(':', field('pattern', $.pattern)))),
    select_expression: $ => prec.dynamic(10, seq('select', '{', items($.select_arm, $), '}')),
    select_arm: $ => seq(choice('_', seq(optional(seq(field('name', choice($._identifier, '_')), '=')), field('operation', $._expression))), '=>', $._expression),
    return_expression: $ => prec.right(seq('return', optional($._expression))),
    scope_expression: $ => prec.dynamic(10, seq('scope', field('name', $._identifier), optional(seq('with', comma($._expression))), $.block)),
    with_expression: $ => prec.dynamic(10, seq('with', '(', items(seq($.qualified_name, ':', $._expression), $), ')', $.block)),
    generate_expression: $ => seq('generate', $.type_arguments, $.block),
    yield_expression: $ => prec.right(seq('yield', $._expression)),
    for_expression: $ => seq('for', optional(choice(
      seq('(', $._for_header, ')'), $._bare_for_header,
    )), $.block),
    // The first line is a generator, which no for { } loop body starts with.
    comprehension_expression: $ => prec.right(seq('for', '{', repeat(semis($)), $.comprehension_generator,
      repeat(seq(repeat1(semis($)), choice($.comprehension_generator, $.comprehension_filter, alias($._comprehension_binding, $.binding)))),
      repeat(semis($)), '}', 'yield', field('value', $._expression))),
    // Besides loop-header bindings, any match pattern; values it does not match are skipped.
    comprehension_generator: $ => seq(choice(prec.dynamic(5, $._iteration_binding), field('pattern', $.pattern)), 'in', field('source', $._expression)),
    comprehension_filter: $ => seq('if', field('condition', $._head_expression)),
    _comprehension_binding: $ => seq(field('name', choice($._identifier, '_', $.tuple_pattern)), optional(seq(':', $.type)), '=', $._expression),
    _iteration_binding: $ => choice(field('name', choice($._identifier, '_')), field('pattern', choice($.tuple_pattern, $.parenthesized_pattern))),
    _for_header: $ => choice(
      seq($._iteration_binding, 'in', $._expression),
      field('condition', $._expression),
      $._loop_clauses,
    ),
    _bare_for_header: $ => choice(
      seq($._iteration_binding, 'in', $._head_expression),
      field('condition', $._head_expression),
      $._head_loop_clauses,
    ),
    _loop_clauses: $ => seq(optional(bindings(field('init', $.loop_binding))), ';', optional(field('condition', $._expression)), ';', optional(bindings(field('update', $.loop_binding)))),
    _head_loop_clauses: $ => seq(optional(bindings(field('init', alias($._head_loop_binding, $.loop_binding)))), ';', optional(field('condition', $._head_expression)), ';', optional(bindings(field('update', alias($._head_loop_binding, $.loop_binding))))),
    loop_binding: $ => seq(field('name', $._identifier), optional(seq(':', $.type)), '=', field('value', $._expression)),
    _head_loop_binding: $ => seq(field('name', $._identifier), optional(seq(':', $.type)), '=', field('value', $._head_expression)),
    comptime_control_expression: $ => prec.dynamic(10, seq('comptime', choice($.for_expression, $.comprehension_expression, $.if_expression, $.match_expression))),
    comptime_expression: $ => prec.dynamic(10, seq('comptime', $.block)),
    mock_expression: $ => prec.dynamic(10, seq('mock', $.qualified_name, $.mock_parameters, $.block)),
    mock_parameters: $ => seq('(', optional(comma(seq(field('name', choice($._identifier, '_'))))), ')'),
    go_body: $ => seq('unsafe', 'go', choice($.string, seq('{', optional($.go_content), '}'))),
  },
});
