id = "bork"
name = "bork"
version = "0.1.0"
schema_version = 1
authors = ["bork contributors"]
description = "bork highlighting and compiler language server"
repository = "https://github.com/GiGurra/bork"

[language_servers.bork]
name = "bork"
languages = ["bork"]

[grammars.bork]
repository = "https://github.com/GiGurra/bork"
rev = "a6b7fe0e69c92660d8770f47acdd0cd57878739a"
path = "editors/tree-sitter-bork"
