id = "bork"
name = "bork"
version = "0.1.0"
schema_version = 1
authors = ["bork contributors"]
description = "bork highlighting and compiler language server"
repository = "https://github.com/GiGurra/bork"

[language_servers.bork]
name = "bork"
languages = ["bork"]

[grammars.bork]
repository = "https://github.com/GiGurra/bork"
rev = "02b6e74bbaf8f4ce7338255259a4abb6ea4c62e1"
path = "editors/tree-sitter-bork"
