id = "bork"
name = "bork"
version = "0.1.0"
schema_version = 1
authors = ["bork contributors"]
description = "bork highlighting and compiler language server"
repository = "https://github.com/GiGurra/bork"

[language_servers.bork]
name = "bork"
languages = ["bork"]

[grammars.bork]
repository = "https://github.com/GiGurra/bork"
rev = "b30b29ee23d4089c7e90ec2c8e323e389ea44db8"
path = "editors/tree-sitter-bork"
