package lsp

import (
	"bytes"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/GiGurra/bork/internal/diag"
	"github.com/GiGurra/bork/internal/driver"
	"golang.org/x/mod/module"
	modzip "golang.org/x/mod/zip"
)

func TestLibraryNavigationAndReadOnlyEdits(t *testing.T) {
	cache, proxy, library, root := t.TempDir(), t.TempDir(), t.TempDir(), t.TempDir()
	t.Cleanup(func() {
		_ = filepath.WalkDir(cache, func(path string, entry fs.DirEntry, err error) error {
			if err == nil && entry.IsDir() {
				return os.Chmod(path, 0o755)
			}
			return err
		})
	})
	t.Setenv("GOMODCACHE", cache)
	t.Setenv("GOPROXY", "file://"+filepath.ToSlash(proxy))
	t.Setenv("GOSUMDB", "off")
	write := func(dir, name, text string) {
		t.Helper()
		if err := os.MkdirAll(dir, 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(filepath.Join(dir, name), []byte(text), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	goMod := "// Code generated by bork deps. DO NOT EDIT.\nmodule example.com/lib\n\ngo 1.26\n"
	libSource := "fn Value(): Int { helper() }\nfn helper(): Int { 41 }\n"
	write(library, "go.mod", goMod)
	write(library, "bork.mod", "module example.com/lib\n")
	write(library, "lib.bork", libSource)
	var archive bytes.Buffer
	if err := modzip.CreateFromDir(&archive, module.Version{Path: "example.com/lib", Version: "v1.0.0"}, library); err != nil {
		t.Fatal(err)
	}
	endpoint := filepath.Join(proxy, "example.com/lib/@v")
	write(endpoint, "v1.0.0.zip", archive.String())
	write(endpoint, "v1.0.0.mod", goMod)
	write(endpoint, "v1.0.0.info", `{"Version":"v1.0.0","Time":"2026-01-01T00:00:00Z"}`)
	write(endpoint, "list", "v1.0.0\n")
	source := "import \"example.com/lib\"\nfn main() uses io { println(lib.Value()) }\n"
	path := filepath.Join(root, "main.bork")
	write(root, "bork.mod", "module example.com/app\n")
	write(root, "main.bork", source)
	if err := driver.Deps(root, "get", []string{"example.com/lib@v1.0.0"}); err != nil {
		t.Fatal(err)
	}
	t.Setenv("GOPROXY", "off")
	s := &server{out: &bytes.Buffer{}, initialized: true, docs: map[string]document{path: {source, 1}}, packages: map[string]*packageState{}, diagnostics: map[string][]diag.Diagnostic{}}
	if err := s.check(); err != nil {
		t.Fatal(err)
	}
	if pkg := s.state(path); pkg == nil || pkg.analysis == nil {
		t.Fatalf("library check: %s", s.out)
	}
	def := query(t, s, path, "definition", 1, 32).(location)
	depPath, err := filePath(def.URI)
	if err != nil || !strings.Contains(depPath, "lib@v1.0.0") || def.Range.Start.Line != 0 {
		t.Fatalf("library definition: %+v, %v", def, err)
	}
	s.docs[depPath] = document{libSource, 1}
	if err := s.check(); err != nil {
		t.Fatal(err)
	}
	if result := query(t, s, depPath, "hover", 0, 18); result == nil {
		t.Fatal("no hover in downloaded source")
	}
	for _, method := range []string{"formatting", "codeAction", "prepareRename", "rename"} {
		if _, err := s.feature("textDocument/"+method, depPath, documentParams{Position: position{1, 4}, NewName: "changed"}); err == nil || !strings.Contains(err.Error(), "read-only") {
			t.Fatalf("%s cache edit: %v", method, err)
		}
	}
	if err := s.validateRename(map[string][]textEdit{def.URI: {{NewText: "changed"}}}); err == nil {
		t.Fatal("rename validation accepted cache edits")
	}
}
