package main

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

func TestNewTemplates(t *testing.T) {
	exe := cliExecutable(t, false)
	for _, template := range []string{"default", "cli", "http", "lib"} {
		t.Run(template, func(t *testing.T) {
			root := t.TempDir()
			cmd := exec.Command(exe, "new", "--template", template, "--module", "example.com/starter", "starter")
			cmd.Dir = root
			out, err := cmd.CombinedOutput()
			if err != nil {
				t.Fatalf("new: %v\n%s", err, out)
			}
			if !strings.Contains(string(out), "cd './starter'") || !strings.Contains(string(out), "bork test .") {
				t.Fatalf("next steps: %s", out)
			}
			dir := filepath.Join(root, "starter")
			for _, name := range []string{"bork.mod", ".gitignore", "README.md"} {
				if _, err := os.Stat(filepath.Join(dir, name)); err != nil {
					t.Fatal(err)
				}
			}
			if template == "lib" {
				data, err := os.ReadFile(filepath.Join(dir, "go.mod"))
				if err != nil || string(data) != "// Code generated by bork deps. DO NOT EDIT.\nmodule example.com/starter\n\ngo 1.26\n" {
					t.Fatalf("library Go manifest: %s (%v)", data, err)
				}
				if data, err := os.ReadFile(filepath.Join(dir, "bork.sum")); err != nil || len(data) != 0 {
					t.Fatalf("library checksums: %s (%v)", data, err)
				}
			}
			for _, args := range [][]string{{"check", "."}, {"test", "."}, {"fmt", "--check", "."}} {
				cmd := exec.Command(exe, args...)
				cmd.Dir = dir
				if out, err := cmd.CombinedOutput(); err != nil {
					t.Fatalf("%v: %v\n%s", args, err, out)
				}
			}
			if template == "default" || template == "cli" {
				args := []string{"run", "."}
				want := "Hello, bork!\n"
				if template == "cli" {
					args = append(args, "--", "Ada")
					want = "Hello, Ada!\n"
				}
				cmd := exec.Command(exe, args...)
				cmd.Dir = dir
				if out, err := cmd.CombinedOutput(); err != nil || string(out) != want {
					t.Fatalf("run: %v\n%s", err, out)
				}
			}
		})
	}
}

func TestNewCLIArguments(t *testing.T) {
	exe := cliExecutable(t, false)
	for _, args := range [][]string{{"new"}, {"new", "--template", "missing", "project"}, {"new", "--module", "bad module", "project"}, {"new", "."}, {"new", "one", "two"}} {
		t.Run(strings.Join(args, " "), func(t *testing.T) {
			root := t.TempDir()
			cmd := exec.Command(exe, args...)
			cmd.Dir = root
			if out, err := cmd.CombinedOutput(); err == nil {
				t.Fatalf("expected failure: %s", out)
			}
			entries, err := os.ReadDir(root)
			if err != nil || len(entries) != 0 {
				t.Fatalf("invalid arguments wrote files: %v (%v)", entries, err)
			}
		})
	}
	t.Run("default and existing destination", func(t *testing.T) {
		root := t.TempDir()
		run := func() ([]byte, error) {
			cmd := exec.Command(exe, "new", "hello")
			cmd.Dir = root
			return cmd.CombinedOutput()
		}
		if out, err := run(); err != nil {
			t.Fatalf("new: %v\n%s", err, out)
		}
		manifest := filepath.Join(root, "hello", "bork.mod")
		want := "module example.com/hello\n"
		if data, err := os.ReadFile(manifest); err != nil || string(data) != want {
			t.Fatalf("manifest: %s (%v)", data, err)
		}
		if out, err := run(); err == nil {
			t.Fatalf("overwrote destination: %s", out)
		}
		if data, err := os.ReadFile(manifest); err != nil || string(data) != want {
			t.Fatalf("changed manifest: %s (%v)", data, err)
		}
	})
}
