// Code generated by genstdvalidators; DO NOT EDIT.
// Runtime support SHA256: 5bae7f6afb7fec2f1ed1c2b49336504ee117f5909a079e5acb5ad1e3fe741f1c
// Code generated by bork. DO NOT EDIT.

package stdvalidators

import (
	"encoding/base64"
	"encoding/hex"
	"encoding/json"
	"fmt"
	_gopkg_fmt "fmt"
	"hash/maphash"
	"math"
	"reflect"
	"strconv"
	_gopkg_strconv "strconv"
	"strings"
	_gopkg_strings "strings"
)

type Ord[T any] struct {
	compare func(T, T) int64
}

type InterpolationValidator[B any] struct {
	validateInterpolation func(StaticParts, []InterpolationHole) []InterpolationIssue
}

type StaticParts struct {
	values []string
}

func (v StaticParts) String() string {
	nativeEnter()
	defer nativeLeave()
	return "StaticParts { values: " +
		func() string {
			nativeStep()
			return _showList[string](v.values, func(x string) string {
				nativeEnter()
				defer nativeLeave()
				return func() string { nativeStep(); return strconv.Quote(x) }()

			})
		}() +
		" }"
}

func (v StaticParts) _borkEqual(other any) bool {
	nativeEnter()
	defer nativeLeave()
	w, ok := other.(StaticParts)
	return ok &&
		func() bool { nativeStep(); return v._equals(w) }()

}

func (v StaticParts) _equals(w StaticParts) bool {
	nativeEnter()
	defer nativeLeave()
	return true &&
		func() bool {
			nativeStep()
			return _equalList[string](v.values, w.values, func(a string, b string) bool {
				nativeEnter()
				defer nativeLeave()
				return a == b
			})
		}()

}

func (v StaticParts) _borkHash() uint64 {
	nativeEnter()
	defer nativeLeave()
	h := uint64(0)
	h = func() uint64 {
		nativeStep()
		return _hashMix(h, func() uint64 {
			nativeStep()
			return _hashList[string](v.values, func(x string) uint64 {
				nativeEnter()
				defer nativeLeave()
				return func() uint64 { nativeStep(); return _hashOf[string](x) }()

			})
		}(),
		)
	}()

	return h
}

type InterpolationKind interface {
	isInterpolationKind()
}

type InterpolationKind_Builtin struct {
	name string
}

func (InterpolationKind_Builtin) isInterpolationKind() {
	nativeEnter()
	defer nativeLeave()
}

func (v InterpolationKind_Builtin) String() string {
	nativeEnter()
	defer nativeLeave()
	return "InterpolationKind.Builtin { name: " +
		func() string { nativeStep(); return strconv.Quote(v.name) }() +
		" }"
}

func (v InterpolationKind_Builtin) _borkEqual(other any) bool {
	nativeEnter()
	defer nativeLeave()
	w, ok := other.(InterpolationKind_Builtin)
	return ok &&
		func() bool { nativeStep(); return v._equals(w) }()

}

func (v InterpolationKind_Builtin) _equals(w InterpolationKind_Builtin) bool {
	nativeEnter()
	defer nativeLeave()
	return true && v.name == w.name
}

func (v InterpolationKind_Builtin) _borkHash() uint64 {
	nativeEnter()
	defer nativeLeave()
	h := uint64(0)
	h = func() uint64 {
		nativeStep()
		return _hashMix(h, func() uint64 { nativeStep(); return _hashOf[string](v.name) }())
	}()

	return h
}

type InterpolationKind_Named struct {
	packagePath string
	name        string
}

func (InterpolationKind_Named) isInterpolationKind() {
	nativeEnter()
	defer nativeLeave()
}

func (v InterpolationKind_Named) String() string {
	nativeEnter()
	defer nativeLeave()
	return "InterpolationKind.Named { packagePath: " +
		func() string { nativeStep(); return strconv.Quote(v.packagePath) }() +
		(", name: " +
			func() string { nativeStep(); return strconv.Quote(v.name) }()) + " }"
}

func (v InterpolationKind_Named) _borkEqual(other any) bool {
	nativeEnter()
	defer nativeLeave()
	w, ok := other.(InterpolationKind_Named)
	return ok &&
		func() bool { nativeStep(); return v._equals(w) }()

}

func (v InterpolationKind_Named) _equals(w InterpolationKind_Named) bool {
	nativeEnter()
	defer nativeLeave()
	return true && v.packagePath == w.packagePath && v.name == w.name
}

func (v InterpolationKind_Named) _borkHash() uint64 {
	nativeEnter()
	defer nativeLeave()
	h := uint64(0)
	h = func() uint64 {
		nativeStep()
		return _hashMix(h, func() uint64 { nativeStep(); return _hashOf[string](v.packagePath) }())
	}()

	h = func() uint64 {
		nativeStep()
		return _hashMix(h, func() uint64 { nativeStep(); return _hashOf[string](v.name) }())
	}()

	return h
}

type InterpolationKind_Unknown struct {
}

func (InterpolationKind_Unknown) isInterpolationKind() {
	nativeEnter()
	defer nativeLeave()
}

func (_ InterpolationKind_Unknown) String() string {
	nativeEnter()
	defer nativeLeave()
	return "InterpolationKind.Unknown"
}

func (v InterpolationKind_Unknown) _borkEqual(other any) bool {
	nativeEnter()
	defer nativeLeave()
	w, ok := other.(InterpolationKind_Unknown)
	return ok &&
		func() bool { nativeStep(); return v._equals(w) }()

}

func (v InterpolationKind_Unknown) _equals(w InterpolationKind_Unknown) bool {
	nativeEnter()
	defer nativeLeave()
	return true
}

func (v InterpolationKind_Unknown) _borkHash() uint64 {
	nativeEnter()
	defer nativeLeave()
	h := uint64(0)
	return h
}

type InterpolationHole struct {
	kinds []InterpolationKind
}

func (v InterpolationHole) String() string {
	nativeEnter()
	defer nativeLeave()
	return "InterpolationHole { kinds: " +
		func() string {
			nativeStep()
			return _showList[InterpolationKind](v.kinds, func(x InterpolationKind) string {
				nativeEnter()
				defer nativeLeave()
				return func() string { nativeStep(); return _show(x) }()

			})
		}() +
		" }"
}

func (v InterpolationHole) _borkEqual(other any) bool {
	nativeEnter()
	defer nativeLeave()
	w, ok := other.(InterpolationHole)
	return ok &&
		func() bool { nativeStep(); return v._equals(w) }()

}

func (v InterpolationHole) _equals(w InterpolationHole) bool {
	nativeEnter()
	defer nativeLeave()
	return true &&
		func() bool {
			nativeStep()
			return _equalList[InterpolationKind](v.kinds, w.kinds, func(a InterpolationKind, b InterpolationKind) bool {
				nativeEnter()
				defer nativeLeave()
				return func() bool { nativeStep(); return _equal(a, b) }()

			})
		}()

}

func (v InterpolationHole) _borkHash() uint64 {
	nativeEnter()
	defer nativeLeave()
	h := uint64(0)
	h = func() uint64 {
		nativeStep()
		return _hashMix(h, func() uint64 {
			nativeStep()
			return _hashList[InterpolationKind](v.kinds, func(x InterpolationKind) uint64 {
				nativeEnter()
				defer nativeLeave()
				return func() uint64 { nativeStep(); return _hash(x) }()

			})
		}(),
		)
	}()

	return h
}

type InterpolationIssue struct {
	hole    Option[int64]
	message string
}

func (v InterpolationIssue) String() string {
	nativeEnter()
	defer nativeLeave()
	return "InterpolationIssue { hole: " +
		func() string { nativeStep(); return _show(v.hole) }() +
		(", message: " +
			func() string { nativeStep(); return strconv.Quote(v.message) }()) + " }"
}

func (v InterpolationIssue) _borkEqual(other any) bool {
	nativeEnter()
	defer nativeLeave()
	w, ok := other.(InterpolationIssue)
	return ok &&
		func() bool { nativeStep(); return v._equals(w) }()

}

func (v InterpolationIssue) _equals(w InterpolationIssue) bool {
	nativeEnter()
	defer nativeLeave()
	return true &&
		func() bool { nativeStep(); return _equal(v.hole, w.hole) }() &&
		v.message == w.message
}

func (v InterpolationIssue) _borkHash() uint64 {
	nativeEnter()
	defer nativeLeave()
	h := uint64(0)
	h = func() uint64 {
		nativeStep()
		return _hashMix(h, func() uint64 { nativeStep(); return _hash(v.hole) }())
	}()

	h = func() uint64 {
		nativeStep()
		return _hashMix(h, func() uint64 { nativeStep(); return _hashOf[string](v.message) }())
	}()

	return h
}

type Option[T any] interface {
	isOption(T)
}

type Option_Some[T any] struct {
	E0 T
}

func (Option_Some[T]) isOption(T) {
	nativeEnter()
	defer nativeLeave()
}

func (v Option_Some[T]) String() string {
	nativeEnter()
	defer nativeLeave()
	return "Option.Some(" +
		func() string { nativeStep(); return _show(v.E0) }() +
		")"
}

func (v Option_Some[T]) _borkEqual(other any) bool {
	nativeEnter()
	defer nativeLeave()
	w, ok := other.(Option_Some[T])
	return ok &&
		func() bool { nativeStep(); return v._equals(w) }()

}

func (v Option_Some[T]) _equals(w Option_Some[T]) bool {
	nativeEnter()
	defer nativeLeave()
	return true &&
		func() bool { nativeStep(); return _equal(v.E0, w.E0) }()

}

func (v Option_Some[T]) _borkHash() uint64 {
	nativeEnter()
	defer nativeLeave()
	h := uint64(0)
	h = func() uint64 {
		nativeStep()
		return _hashMix(h, func() uint64 { nativeStep(); return _hash(v.E0) }())
	}()

	return h
}

type Option_None[T any] struct {
}

func (Option_None[T]) isOption(T) {
	nativeEnter()
	defer nativeLeave()
}

func (_ Option_None[T]) String() string {
	nativeEnter()
	defer nativeLeave()
	return "Option.None"
}

func (v Option_None[T]) _borkEqual(other any) bool {
	nativeEnter()
	defer nativeLeave()
	w, ok := other.(Option_None[T])
	return ok &&
		func() bool { nativeStep(); return v._equals(w) }()

}

func (v Option_None[T]) _equals(w Option_None[T]) bool {
	nativeEnter()
	defer nativeLeave()
	return true
}

func (v Option_None[T]) _borkHash() uint64 {
	nativeEnter()
	defer nativeLeave()
	h := uint64(0)
	return h
}

type _sql_Dialect interface {
	is_sql_Dialect()
}

type _sql_Dialect_Sqlite struct {
}

func (_sql_Dialect_Sqlite) is_sql_Dialect() {
	nativeEnter()
	defer nativeLeave()
}

func (_ _sql_Dialect_Sqlite) String() string {
	nativeEnter()
	defer nativeLeave()
	return "Dialect.Sqlite"
}

func (v _sql_Dialect_Sqlite) _borkEqual(other any) bool {
	nativeEnter()
	defer nativeLeave()
	w, ok := other.(_sql_Dialect_Sqlite)
	return ok &&
		func() bool { nativeStep(); return v._equals(w) }()

}

func (v _sql_Dialect_Sqlite) _equals(w _sql_Dialect_Sqlite) bool {
	nativeEnter()
	defer nativeLeave()
	return true
}

func (v _sql_Dialect_Sqlite) _borkHash() uint64 {
	nativeEnter()
	defer nativeLeave()
	h := uint64(0)
	return h
}

type _sql_Dialect_Postgres struct {
}

func (_sql_Dialect_Postgres) is_sql_Dialect() {
	nativeEnter()
	defer nativeLeave()
}

func (_ _sql_Dialect_Postgres) String() string {
	nativeEnter()
	defer nativeLeave()
	return "Dialect.Postgres"
}

func (v _sql_Dialect_Postgres) _borkEqual(other any) bool {
	nativeEnter()
	defer nativeLeave()
	w, ok := other.(_sql_Dialect_Postgres)
	return ok &&
		func() bool { nativeStep(); return v._equals(w) }()

}

func (v _sql_Dialect_Postgres) _equals(w _sql_Dialect_Postgres) bool {
	nativeEnter()
	defer nativeLeave()
	return true
}

func (v _sql_Dialect_Postgres) _borkHash() uint64 {
	nativeEnter()
	defer nativeLeave()
	h := uint64(0)
	return h
}

type _sql_Rendered struct {
	query  string
	params []any
}

func (v _sql_Rendered) String() string {
	nativeEnter()
	defer nativeLeave()
	return "Rendered { query: " +
		func() string { nativeStep(); return strconv.Quote(v.query) }() +
		(", params: " +
			func() string {
				nativeStep()
				return _showList[any](v.params, func(x any) string {
					nativeEnter()
					defer nativeLeave()
					return func() string { nativeStep(); return _show(x) }()

				})
			}()) + " }"
}

func (v _sql_Rendered) _borkEqual(other any) bool {
	nativeEnter()
	defer nativeLeave()
	w, ok := other.(_sql_Rendered)
	return ok &&
		func() bool { nativeStep(); return v._equals(w) }()

}

func (v _sql_Rendered) _equals(w _sql_Rendered) bool {
	nativeEnter()
	defer nativeLeave()
	return true && v.query == w.query &&
		func() bool {
			nativeStep()
			return _equalList[any](v.params, w.params, func(a any, b any) bool {
				nativeEnter()
				defer nativeLeave()
				return func() bool { nativeStep(); return _equal(a, b) }()

			})
		}()

}

func (v _sql_Rendered) _borkHash() uint64 {
	nativeEnter()
	defer nativeLeave()
	h := uint64(0)
	h = func() uint64 {
		nativeStep()
		return _hashMix(h, func() uint64 { nativeStep(); return _hashOf[string](v.query) }())
	}()

	h = func() uint64 {
		nativeStep()
		return _hashMix(h, func() uint64 {
			nativeStep()
			return _hashList[any](v.params, func(x any) uint64 {
				nativeEnter()
				defer nativeLeave()
				return func() uint64 { nativeStep(); return _hash(x) }()

			})
		}(),
		)
	}()

	return h
}

type _sql_segment interface {
	is_sql_segment()
}

type _sql_segment_text struct {
	value string
}

func (_sql_segment_text) is_sql_segment() {
	nativeEnter()
	defer nativeLeave()
}

func (v _sql_segment_text) String() string {
	nativeEnter()
	defer nativeLeave()
	return "segment.text { value: " +
		func() string { nativeStep(); return strconv.Quote(v.value) }() +
		" }"
}

func (v _sql_segment_text) _borkEqual(other any) bool {
	nativeEnter()
	defer nativeLeave()
	w, ok := other.(_sql_segment_text)
	return ok &&
		func() bool { nativeStep(); return v._equals(w) }()

}

func (v _sql_segment_text) _equals(w _sql_segment_text) bool {
	nativeEnter()
	defer nativeLeave()
	return true && v.value == w.value
}

func (v _sql_segment_text) _borkHash() uint64 {
	nativeEnter()
	defer nativeLeave()
	h := uint64(0)
	h = func() uint64 {
		nativeStep()
		return _hashMix(h, func() uint64 { nativeStep(); return _hashOf[string](v.value) }())
	}()

	return h
}

type _sql_segment_bound struct {
	value any
}

func (_sql_segment_bound) is_sql_segment() {
	nativeEnter()
	defer nativeLeave()
}

func (v _sql_segment_bound) String() string {
	nativeEnter()
	defer nativeLeave()
	return "segment.bound { value: " +
		func() string { nativeStep(); return _show(v.value) }() +
		" }"
}

func (v _sql_segment_bound) _borkEqual(other any) bool {
	nativeEnter()
	defer nativeLeave()
	w, ok := other.(_sql_segment_bound)
	return ok &&
		func() bool { nativeStep(); return v._equals(w) }()

}

func (v _sql_segment_bound) _equals(w _sql_segment_bound) bool {
	nativeEnter()
	defer nativeLeave()
	return true &&
		func() bool { nativeStep(); return _equal(v.value, w.value) }()

}

func (v _sql_segment_bound) _borkHash() uint64 {
	nativeEnter()
	defer nativeLeave()
	h := uint64(0)
	h = func() uint64 {
		nativeStep()
		return _hashMix(h, func() uint64 { nativeStep(); return _hash(v.value) }())
	}()

	return h
}

type _sql_segment_name struct {
	value string
}

func (_sql_segment_name) is_sql_segment() {
	nativeEnter()
	defer nativeLeave()
}

func (v _sql_segment_name) String() string {
	nativeEnter()
	defer nativeLeave()
	return "segment.name { value: " +
		func() string { nativeStep(); return strconv.Quote(v.value) }() +
		" }"
}

func (v _sql_segment_name) _borkEqual(other any) bool {
	nativeEnter()
	defer nativeLeave()
	w, ok := other.(_sql_segment_name)
	return ok &&
		func() bool { nativeStep(); return v._equals(w) }()

}

func (v _sql_segment_name) _equals(w _sql_segment_name) bool {
	nativeEnter()
	defer nativeLeave()
	return true && v.value == w.value
}

func (v _sql_segment_name) _borkHash() uint64 {
	nativeEnter()
	defer nativeLeave()
	h := uint64(0)
	h = func() uint64 {
		nativeStep()
		return _hashMix(h, func() uint64 { nativeStep(); return _hashOf[string](v.value) }())
	}()

	return h
}

type _sql_Statement struct {
	segments []_sql_segment
}

func (v _sql_Statement) String() string {
	nativeEnter()
	defer nativeLeave()
	return "Statement { segments: " +
		func() string {
			nativeStep()
			return _showList[_sql_segment](v.segments, func(x _sql_segment) string {
				nativeEnter()
				defer nativeLeave()
				return func() string { nativeStep(); return _show(x) }()

			})
		}() +
		" }"
}

func (v _sql_Statement) _borkEqual(other any) bool {
	nativeEnter()
	defer nativeLeave()
	w, ok := other.(_sql_Statement)
	return ok &&
		func() bool { nativeStep(); return v._equals(w) }()

}

func (v _sql_Statement) _equals(w _sql_Statement) bool {
	nativeEnter()
	defer nativeLeave()
	return true &&
		func() bool {
			nativeStep()
			return _equalList[_sql_segment](v.segments, w.segments, func(a _sql_segment, b _sql_segment) bool {
				nativeEnter()
				defer nativeLeave()
				return func() bool { nativeStep(); return _equal(a, b) }()

			})
		}()

}

func (v _sql_Statement) _borkHash() uint64 {
	nativeEnter()
	defer nativeLeave()
	h := uint64(0)
	h = func() uint64 {
		nativeStep()
		return _hashMix(h, func() uint64 {
			nativeStep()
			return _hashList[_sql_segment](v.segments, func(x _sql_segment) uint64 {
				nativeEnter()
				defer nativeLeave()
				return func() uint64 { nativeStep(); return _hash(x) }()

			})
		}(),
		)
	}()

	return h
}

type _sql_Builder struct {
	parts    StaticParts
	index    int64
	segments []_sql_segment
}

func (v _sql_Builder) String() string {
	nativeEnter()
	defer nativeLeave()
	return "Builder { parts: " +
		func() string { nativeStep(); return _show(v.parts) }() +
		(", index: " +
			func() string { nativeStep(); return strconv.FormatInt(int64(v.index), 10) }()) + (", segments: " +
		func() string {
			nativeStep()
			return _showList[_sql_segment](v.segments, func(x _sql_segment) string {
				nativeEnter()
				defer nativeLeave()
				return func() string { nativeStep(); return _show(x) }()

			})
		}()) + " }"
}

func (v _sql_Builder) _borkEqual(other any) bool {
	nativeEnter()
	defer nativeLeave()
	w, ok := other.(_sql_Builder)
	return ok &&
		func() bool { nativeStep(); return v._equals(w) }()

}

func (v _sql_Builder) _equals(w _sql_Builder) bool {
	nativeEnter()
	defer nativeLeave()
	return true &&
		func() bool { nativeStep(); return v.parts._equals(w.parts) }() &&
		v.index == w.index &&
		func() bool {
			nativeStep()
			return _equalList[_sql_segment](v.segments, w.segments, func(a _sql_segment, b _sql_segment) bool {
				nativeEnter()
				defer nativeLeave()
				return func() bool { nativeStep(); return _equal(a, b) }()

			})
		}()

}

func (v _sql_Builder) _borkHash() uint64 {
	nativeEnter()
	defer nativeLeave()
	h := uint64(0)
	h = func() uint64 {
		nativeStep()
		return _hashMix(h, func() uint64 { nativeStep(); return v.parts._borkHash() }())
	}()

	h = func() uint64 {
		nativeStep()
		return _hashMix(h, func() uint64 { nativeStep(); return _hashOf[int64](v.index) }())
	}()

	h = func() uint64 {
		nativeStep()
		return _hashMix(h, func() uint64 {
			nativeStep()
			return _hashList[_sql_segment](v.segments, func(x _sql_segment) uint64 {
				nativeEnter()
				defer nativeLeave()
				return func() uint64 { nativeStep(); return _hash(x) }()

			})
		}(),
		)
	}()

	return h
}

type _sql_scanError struct {
	detail     _sql_Error
	hole       int64
	incomplete bool
}

func (v _sql_scanError) String() string {
	nativeEnter()
	defer nativeLeave()
	return "scanError { detail: " +
		func() string { nativeStep(); return _show(v.detail) }() +
		(", hole: " +
			func() string { nativeStep(); return strconv.FormatInt(int64(v.hole), 10) }()) + (", incomplete: " +
		func() string { nativeStep(); return strconv.FormatBool(v.incomplete) }()) + " }"
}

func (v _sql_scanError) _borkEqual(other any) bool {
	nativeEnter()
	defer nativeLeave()
	w, ok := other.(_sql_scanError)
	return ok &&
		func() bool { nativeStep(); return v._equals(w) }()

}

func (v _sql_scanError) _equals(w _sql_scanError) bool {
	nativeEnter()
	defer nativeLeave()
	return true &&
		func() bool { nativeStep(); return v.detail._equals(w.detail) }() &&
		v.hole == w.hole && v.incomplete == w.incomplete
}

func (v _sql_scanError) _borkHash() uint64 {
	nativeEnter()
	defer nativeLeave()
	h := uint64(0)
	h = func() uint64 {
		nativeStep()
		return _hashMix(h, func() uint64 { nativeStep(); return v.detail._borkHash() }())
	}()

	h = func() uint64 {
		nativeStep()
		return _hashMix(h, func() uint64 { nativeStep(); return _hashOf[int64](v.hole) }())
	}()

	h = func() uint64 {
		nativeStep()
		return _hashMix(h, func() uint64 { nativeStep(); return _hashOf[bool](v.incomplete) }())
	}()

	return h
}

type _sql_Error struct {
	operation string
	message   string
}

func (v _sql_Error) String() string {
	nativeEnter()
	defer nativeLeave()
	return "Error { operation: " +
		func() string { nativeStep(); return strconv.Quote(v.operation) }() +
		(", message: " +
			func() string { nativeStep(); return strconv.Quote(v.message) }()) + " }"
}

func (v _sql_Error) _borkEqual(other any) bool {
	nativeEnter()
	defer nativeLeave()
	w, ok := other.(_sql_Error)
	return ok &&
		func() bool { nativeStep(); return v._equals(w) }()

}

func (v _sql_Error) _equals(w _sql_Error) bool {
	nativeEnter()
	defer nativeLeave()
	return true && v.operation == w.operation && v.message == w.message
}

func (v _sql_Error) _borkHash() uint64 {
	nativeEnter()
	defer nativeLeave()
	h := uint64(0)
	h = func() uint64 {
		nativeStep()
		return _hashMix(h, func() uint64 { nativeStep(); return _hashOf[string](v.operation) }())
	}()

	h = func() uint64 {
		nativeStep()
		return _hashMix(h, func() uint64 { nativeStep(); return _hashOf[string](v.message) }())
	}()

	return h
}

type _sql_Null struct {
}

func (_ _sql_Null) String() string {
	nativeEnter()
	defer nativeLeave()
	return "Null {}"
}

func (v _sql_Null) _borkEqual(other any) bool {
	nativeEnter()
	defer nativeLeave()
	w, ok := other.(_sql_Null)
	return ok &&
		func() bool { nativeStep(); return v._equals(w) }()

}

func (v _sql_Null) _equals(w _sql_Null) bool {
	nativeEnter()
	defer nativeLeave()
	return true
}

func (v _sql_Null) _borkHash() uint64 {
	nativeEnter()
	defer nativeLeave()
	h := uint64(0)
	return h
}

func _i_sql_sqlInterpolationValidator_validateInterpolation(parts StaticParts, holes []InterpolationHole) []InterpolationIssue {
	nativeEnter()
	defer nativeLeave()
	return func() []InterpolationIssue {
		nativeStep()
		return _sql_validateSQL(parts, holes)
	}()

}

func _i_sql_sqlInterpolationValidator() InterpolationValidator[_sql_Builder] {
	nativeEnter()
	defer nativeLeave()
	return InterpolationValidator[_sql_Builder]{validateInterpolation: _i_sql_sqlInterpolationValidator_validateInterpolation}
}

func _ctEncode4(value int64, depth int) _ctValue {
	nativeEnter()
	defer nativeLeave()
	func() { nativeStep(); _ctCheck(depth, "Int") }()

	return _ctValue{Kind: "Int", Text: func() string { nativeStep(); return strconv.FormatInt(int64(value), 10) }()}
}

func _ctEncode3(value Option[int64], depth int) _ctValue {
	nativeEnter()
	defer nativeLeave()
	func() { nativeStep(); _ctCheck(depth, "Option[Int]") }()

	switch value := value.(type) {
	case Option_Some[int64]:
		_ = value
		func() {
			nativeStep()

			_ctReserve(6 *
				func() int { nativeStep(); return len("Some") }(),
			)
		}()

		return _ctValue{Kind: "Option[Int]", Tag: "Some", Items: []_ctValue{func() _ctValue { nativeStep(); return _ctEncode4(value.E0, depth+1) }()}}
	case Option_None[int64]:
		_ = value
		func() {
			nativeStep()

			_ctReserve(6 *
				func() int { nativeStep(); return len("None") }(),
			)
		}()

		return _ctValue{Kind: "Option[Int]", Tag: "None", Items: []_ctValue{}}
	default:
		panic("invalid comptime sealed value")
	}
}

func _ctEncode5(value string, depth int) _ctValue {
	nativeEnter()
	defer nativeLeave()
	func() { nativeStep(); _ctCheck(depth, "String") }()

	if func() int { nativeStep(); return len(value) }() >
		_ctBudget {
		panic("comptime result exceeds 16 MiB")
	}
	func() {
		nativeStep()

		_ctReserve(func() int {
			nativeStep()
			return base64.StdEncoding.EncodedLen(func() int { nativeStep(); return len(value) }())
		}(),
		)
	}()

	return _ctValue{Kind: "String", Text: func() string { nativeStep(); return base64.StdEncoding.EncodeToString([]byte(value)) }()}
}

func _ctEncode2(value InterpolationIssue, depth int) _ctValue {
	nativeEnter()
	defer nativeLeave()
	func() { nativeStep(); _ctCheck(depth, "InterpolationIssue") }()

	return _ctValue{Kind: "InterpolationIssue", Items: []_ctValue{func() _ctValue { nativeStep(); return _ctEncode3(value.hole, depth+1) }(), func() _ctValue { nativeStep(); return _ctEncode5(value.message, depth+1) }()}}
}

func _ctEncode1(value []InterpolationIssue, depth int) _ctValue {
	nativeEnter()
	defer nativeLeave()
	func() { nativeStep(); _ctCheck(depth, "List[InterpolationIssue]") }()

	if func() int { nativeStep(); return len(value) }() >
		_ctNodeLimit-_ctNodes {
		panic("comptime result exceeds node limit")
	}
	out := _ctValue{Kind: "List[InterpolationIssue]", Nil: value == nil}
	for _, item := range value {
		nativeStep()
		out.Items = func(_arg0 []_ctValue, _arg1 _ctValue) []_ctValue {
			nativeStep()
			nativeAllocate(64)
			return append(_arg0, _arg1)
		}(out.Items, func() _ctValue { nativeStep(); return _ctEncode2(item, depth+1) }())

	}
	return out
}

func _ctEncode0(value [][]InterpolationIssue, depth int) _ctValue {
	nativeEnter()
	defer nativeLeave()
	func() { nativeStep(); _ctCheck(depth, "List[List[InterpolationIssue]]") }()

	if func() int { nativeStep(); return len(value) }() >
		_ctNodeLimit-_ctNodes {
		panic("comptime result exceeds node limit")
	}
	out := _ctValue{Kind: "List[List[InterpolationIssue]]", Nil: value == nil}
	for _, item := range value {
		nativeStep()
		out.Items = func(_arg0 []_ctValue, _arg1 _ctValue) []_ctValue {
			nativeStep()
			nativeAllocate(64)
			return append(_arg0, _arg1)
		}(out.Items, func() _ctValue { nativeStep(); return _ctEncode1(item, depth+1) }())

	}
	return out
}

type _ctValue struct {
	Kind  string
	Text  string
	Tag   string
	Items []_ctValue
	Nil   bool
}

var _ctNodes int

var _ctBudget = _ctResultLimit - 128

func _ctReserve(size int) {
	nativeEnter()
	defer nativeLeave()
	if size > _ctBudget {
		panic("comptime result exceeds 16 MiB")
	}
	_ctBudget -= size
}

func _ctCheck(depth int, kind string) {
	nativeEnter()
	defer nativeLeave()
	func() {
		nativeStep()

		_ctReserve(80 + 6*
			func() int { nativeStep(); return len(kind) }(),
		)
	}()

	if depth > _ctDepthLimit {
		panic("comptime result exceeds depth limit")
	}
	_ctNodes++
	if _ctNodes > _ctNodeLimit {
		panic("comptime result exceeds node limit")
	}
}

const (
	_ctSchemaVersion = 2
	_ctResultLimit   = 16777216
	_ctNodeLimit     = 1000000
	_ctDepthLimit    = 256
)

func artifactHoles(values [][]Kind) []InterpolationHole {
	nativeEnter()
	defer nativeLeave()
	out := []InterpolationHole{}
	for _, values := range values {
		nativeStep()
		kinds := []InterpolationKind{}
		for _, value := range values {
			nativeStep()
			switch value.Tag {
			case "Builtin":
				kinds = func(_arg0 []InterpolationKind, _arg1 InterpolationKind) []InterpolationKind {
					nativeStep()
					nativeAllocate(64)
					return append(_arg0, _arg1)
				}(kinds, InterpolationKind_Builtin{name: value.Name})
			case "Named":
				kinds = func(_arg0 []InterpolationKind, _arg1 InterpolationKind) []InterpolationKind {
					nativeStep()
					nativeAllocate(64)
					return append(_arg0, _arg1)
				}(kinds, InterpolationKind_Named{packagePath: value.PackagePath, name: value.Name})
			case "Unknown":
				kinds = func(_arg0 []InterpolationKind, _arg1 InterpolationKind) []InterpolationKind {
					nativeStep()
					nativeAllocate(64)
					return append(_arg0, _arg1)
				}(kinds, InterpolationKind_Unknown{})
			default:
				panic("invalid standard validator kind")
			}
		}
		out = func(_arg0 []InterpolationHole, _arg1 InterpolationHole) []InterpolationHole {
			nativeStep()
			nativeAllocate(64)
			return append(_arg0, _arg1)
		}(out, InterpolationHole{kinds: kinds})
	}
	return out
}

func artifactCall(index int, request Request) []InterpolationIssue {
	nativeEnter()
	defer nativeLeave()
	switch index {
	case 0:
		return func() []InterpolationIssue {
			nativeStep()
			return _i_sql_sqlInterpolationValidator_validateInterpolation(StaticParts{values: request.Parts}, func() []InterpolationHole {
				nativeStep()
				return artifactHoles(request.Holes)
			}(),
			)
		}()

	}
	panic("invalid artifact index")
}

func init() {
	descriptors = []Descriptor{{Package: "bork/sql", Instance: "sqlInterpolationValidator", Builder: "Builder", Signature: "(StaticParts,List[InterpolationHole])->List[InterpolationIssue]", Identity: "e4840bd01a37d8c074b71dcf33c4578974cdd22dfde652fed58c0cd9acbc0eb3", Sources: []Source{{Path: "prelude/classes.bork", Digest: "303b8b27423bddad847f15f6965e6ceb9acf0a8fb5f881b59a92c4f8cd865896"}, {Path: "prelude/interpolation.bork", Digest: "3bcb0d676886a4f05ecb2889ae0883690f3c9e3597e2faf9fac5b7339d88fba5"}, {Path: "prelude/options.bork", Digest: "19d8b82007ae3cab025a7f6e92f28165481d2f10ac1b711bb4faa35e1949f0e1"}, {Path: "bork/sql/interpolation.bork", Digest: "129be28fdfefb980941b9e1f67a1d0f4df1816ece99f6e4dfa5f8b1f92f1c6cc"}, {Path: "bork/sql/sql.bork", Digest: "17ccdca7ca4ee537f536a15519a1cb0b0b7d069ec252aaf0aec16db85558c462"}}, Definitions: []Source{{Path: "bork/sql/interpolation.bork:166:3", Digest: "273acf8a10e01d829d062fa9aa488f329b486db9ff2fffaa6aec746508df5275"}, {Path: "bork/sql/interpolation.bork:170:1", Digest: "1a73c5327d689e7013876ffc55762bcb8e3d4a410df5a4491b5d48100cd7d9bc"}, {Path: "bork/sql/interpolation.bork:34:1", Digest: "dea4ef18c068ecb9b038339c45cb25314d39bdf464cd0552ecbcb0fd8520ffef"}}}}
	nativeEvaluation = func(calls []Call) []byte {
		nativeEnter()
		defer nativeLeave()
		_ctBudget = _ctResultLimit - 128
		_ctNodes = 0
		values := [][]InterpolationIssue{}
		for _, call := range calls {
			nativeStep()
			values = func(_arg0 [][]InterpolationIssue, _arg1 []InterpolationIssue) [][]InterpolationIssue {
				nativeStep()
				nativeAllocate(64)
				return append(_arg0, _arg1)
			}(values, func() []InterpolationIssue {
				nativeStep()
				return artifactCall(call.Binding.index, call.Request)
			}())

		}
		data, err := func() ([]byte, error) {
			nativeStep()
			return json.Marshal(struct {
				Version int
				Value   _ctValue
			}{_ctSchemaVersion, func() _ctValue { nativeStep(); return _ctEncode0(values, 0) }()})
		}()

		if err != nil {
			panic(err)
		}
		if func() int { nativeStep(); return len(data) }() >
			_ctResultLimit {
			panic("comptime result exceeds 16 MiB")
		}
		return data
	}
}

// bork runtime

type _Bytes []byte

func (b _Bytes) String() string {
	nativeEnter()
	defer nativeLeave()
	return "Bytes(" +
		func() string { nativeStep(); return hex.EncodeToString(b) }() +
		")"
}

var _mapSeed = maphash.MakeSeed()

func _hashMix(a, b uint64) uint64 {
	nativeEnter()
	defer nativeLeave()
	return (a ^ (b + 0x9e3779b97f4a7c15 + (a << 6) + (a >> 2))) * 0xbf58476d1ce4e5b9
}

func _hash(x any) uint64 {
	nativeEnter()
	defer nativeLeave()
	if v, ok := x.(interface{ _borkHash() uint64 }); ok {
		return func() uint64 { nativeStep(); return v._borkHash() }()

	}
	switch x := x.(type) {
	case nil:
		return 0
	case bool:
		return func() uint64 { nativeStep(); return maphash.Comparable(_mapSeed, x) }()

	case string:
		return func() uint64 { nativeStep(); return maphash.Comparable(_mapSeed, x) }()

	case int64:
		return func() uint64 { nativeStep(); return maphash.Comparable(_mapSeed, x) }()

	case int32:
		return func() uint64 { nativeStep(); return maphash.Comparable(_mapSeed, x) }()

	case int16:
		return func() uint64 { nativeStep(); return maphash.Comparable(_mapSeed, x) }()

	case int8:
		return func() uint64 { nativeStep(); return maphash.Comparable(_mapSeed, x) }()

	case uint64:
		return func() uint64 { nativeStep(); return maphash.Comparable(_mapSeed, x) }()

	case uint32:
		return func() uint64 { nativeStep(); return maphash.Comparable(_mapSeed, x) }()

	case uint16:
		return func() uint64 { nativeStep(); return maphash.Comparable(_mapSeed, x) }()

	case uint8:
		return func() uint64 { nativeStep(); return maphash.Comparable(_mapSeed, x) }()

	case float64:
		return func() uint64 { nativeStep(); return maphash.Comparable(_mapSeed, x) }()

	case float32:
		return func() uint64 { nativeStep(); return maphash.Comparable(_mapSeed, x) }()

	}
	return func() uint64 {
		nativeStep()
		return _hashValue(func() reflect.Value { nativeStep(); return reflect.ValueOf(x) }())
	}()

}

func _hashOf[T comparable](x T) uint64 {
	nativeEnter()
	defer nativeLeave()
	return func() uint64 { nativeStep(); return maphash.Comparable(_mapSeed, x) }()

}

func _hashList[T any](xs []T, hash func(T) uint64) uint64 {
	nativeEnter()
	defer nativeLeave()
	var h uint64
	for _, x := range xs {
		nativeStep()
		h = func() uint64 {
			nativeStep()
			return _hashMix(h, func() uint64 { nativeStep(); return hash(x) }())
		}()

	}
	return h
}

func _hashValue(v reflect.Value) uint64 {
	nativeEnter()
	defer nativeLeave()
	if !func() bool { nativeStep(); return v.IsValid() }() {
		return 0
	}
	if func() reflect.Kind { nativeStep(); return v.Kind() }() ==
		reflect.Struct &&
		func() bool { nativeStep(); return v.CanInterface() }() {
		if x, ok := func() any { nativeStep(); return v.Interface() }().(interface{ _borkHash() uint64 }); ok {
			return func() uint64 { nativeStep(); return x._borkHash() }()

		}
	}
	switch func() reflect.Kind { nativeStep(); return v.Kind() }() {
	case reflect.Interface:
		if func() bool { nativeStep(); return v.IsNil() }() {
			return 0
		}
		return func() uint64 {
			nativeStep()
			return _hashValue(func() reflect.Value { nativeStep(); return v.Elem() }())
		}()

	case reflect.Slice:
		var h uint64
		for i := 0; i <
			func() int { nativeStep(); return v.Len() }(); i++ {
			nativeStep()
			h = func() uint64 {
				nativeStep()
				return _hashMix(h, func() uint64 {
					nativeStep()
					return _hashValue(func() reflect.Value { nativeStep(); return v.Index(i) }())
				}(),
				)
			}()

		}
		return h
	case reflect.Struct:
		var h uint64
		for i := 0; i <
			func() int { nativeStep(); return v.NumField() }(); i++ {
			nativeStep()
			h = func() uint64 {
				nativeStep()
				return _hashMix(h, func() uint64 {
					nativeStep()
					return _hashValue(func() reflect.Value { nativeStep(); return v.Field(i) }())
				}(),
				)
			}()

		}
		return h
	case reflect.Bool:
		return func() uint64 {
			nativeStep()
			return maphash.Comparable(_mapSeed, func() bool { nativeStep(); return v.Bool() }())
		}()

	case reflect.String:
		return func() uint64 {
			nativeStep()
			return maphash.Comparable(_mapSeed, func() string { nativeStep(); return v.String() }())
		}()

	case reflect.Int:
		return func() uint64 {
			nativeStep()
			return maphash.Comparable(_mapSeed, func() int64 { nativeStep(); return v.Int() }())
		}()

	case reflect.Int64:
		return func() uint64 {
			nativeStep()
			return maphash.Comparable(_mapSeed, func() int64 { nativeStep(); return v.Int() }())
		}()

	case reflect.Int32:
		return func() uint64 {
			nativeStep()
			return maphash.Comparable(_mapSeed, int32(func() int64 { nativeStep(); return v.Int() }()))
		}()

	case reflect.Int16:
		return func() uint64 {
			nativeStep()
			return maphash.Comparable(_mapSeed, int16(func() int64 { nativeStep(); return v.Int() }()))
		}()

	case reflect.Int8:
		return func() uint64 {
			nativeStep()
			return maphash.Comparable(_mapSeed, int8(func() int64 { nativeStep(); return v.Int() }()))
		}()

	case reflect.Uint:
		return func() uint64 {
			nativeStep()
			return maphash.Comparable(_mapSeed, func() uint64 { nativeStep(); return v.Uint() }())
		}()

	case reflect.Uint64:
		return func() uint64 {
			nativeStep()
			return maphash.Comparable(_mapSeed, func() uint64 { nativeStep(); return v.Uint() }())
		}()

	case reflect.Uint32:
		return func() uint64 {
			nativeStep()
			return maphash.Comparable(_mapSeed, uint32(func() uint64 { nativeStep(); return v.Uint() }()))
		}()

	case reflect.Uint16:
		return func() uint64 {
			nativeStep()
			return maphash.Comparable(_mapSeed, uint16(func() uint64 { nativeStep(); return v.Uint() }()))
		}()

	case reflect.Uint8:
		return func() uint64 {
			nativeStep()
			return maphash.Comparable(_mapSeed, uint8(func() uint64 { nativeStep(); return v.Uint() }()))
		}()

	case reflect.Float64:
		return func() uint64 {
			nativeStep()
			return maphash.Comparable(_mapSeed, func() float64 { nativeStep(); return v.Float() }())
		}()

	case reflect.Float32:
		return func() uint64 {
			nativeStep()
			return maphash.Comparable(_mapSeed, float32(func() float64 { nativeStep(); return v.Float() }()))
		}()

	}
	panic("bork: cannot hash this value")
}

func _equal(a, b any) bool {
	nativeEnter()
	defer nativeLeave()
	if x, ok := a.(interface{ _borkEqual(any) bool }); ok {
		return func() bool { nativeStep(); return x._borkEqual(b) }()

	}
	switch x := a.(type) {
	case nil:
		return b == nil
	case bool:
		y, ok := b.(bool)
		return ok && x == y
	case string:
		y, ok := b.(string)
		return ok && x == y
	case int64:
		y, ok := b.(int64)
		return ok && x == y
	case int32:
		y, ok := b.(int32)
		return ok && x == y
	case int16:
		y, ok := b.(int16)
		return ok && x == y
	case int8:
		y, ok := b.(int8)
		return ok && x == y
	case uint64:
		y, ok := b.(uint64)
		return ok && x == y
	case uint32:
		y, ok := b.(uint32)
		return ok && x == y
	case uint16:
		y, ok := b.(uint16)
		return ok && x == y
	case uint8:
		y, ok := b.(uint8)
		return ok && x == y
	case float64:
		y, ok := b.(float64)
		return ok && x == y
	case float32:
		y, ok := b.(float32)
		return ok && x == y
	}
	return func() bool {
		nativeStep()
		return _equalValues(func() reflect.Value { nativeStep(); return reflect.ValueOf(a) }(), func() reflect.Value { nativeStep(); return reflect.ValueOf(b) }())
	}()

}

func _equalList[T any](a, b []T, equal func(T, T) bool) bool {
	nativeEnter()
	defer nativeLeave()
	if func() int { nativeStep(); return len(a) }() != func() int { nativeStep(); return len(b) }() {
		return false
	}
	for i := range a {
		nativeStep()
		if !func() bool { nativeStep(); return equal(a[i], b[i]) }() {
			return false
		}
	}
	return true
}

func _equalValues(x, y reflect.Value) bool {
	nativeEnter()
	defer nativeLeave()
	if !func() bool { nativeStep(); return x.IsValid() }() ||
		!func() bool { nativeStep(); return y.IsValid() }() {
		return func() bool { nativeStep(); return x.IsValid() }() == func() bool { nativeStep(); return y.IsValid() }()

	}
	if func() reflect.Type { nativeStep(); return x.Type() }() != func() reflect.Type { nativeStep(); return y.Type() }() {
		return false
	}
	if func() reflect.Kind { nativeStep(); return x.Kind() }() ==
		reflect.Struct &&
		func() bool { nativeStep(); return x.CanInterface() }() {
		if v, ok := func() any { nativeStep(); return x.Interface() }().(interface{ _borkEqual(any) bool }); ok &&
			func() bool { nativeStep(); return y.CanInterface() }() {
			return func() bool {
				nativeStep()
				return v._borkEqual(func() any { nativeStep(); return y.Interface() }())
			}()

		}
	}
	switch func() reflect.Kind { nativeStep(); return x.Kind() }() {
	case reflect.Interface:
		if func() bool { nativeStep(); return x.IsNil() }() || func() bool { nativeStep(); return y.IsNil() }() {
			return func() bool { nativeStep(); return x.IsNil() }() == func() bool { nativeStep(); return y.IsNil() }()

		}
		return func() bool {
			nativeStep()
			return _equalValues(func() reflect.Value { nativeStep(); return x.Elem() }(), func() reflect.Value { nativeStep(); return y.Elem() }())
		}()

	case reflect.Slice:
		if func() int { nativeStep(); return x.Len() }() != func() int { nativeStep(); return y.Len() }() {
			return false
		}
		for i := 0; i <
			func() int { nativeStep(); return x.Len() }(); i++ {
			nativeStep()
			if !func() bool {
				nativeStep()
				return _equalValues(func() reflect.Value { nativeStep(); return x.Index(i) }(), func() reflect.Value { nativeStep(); return y.Index(i) }())
			}() {
				return false
			}
		}
		return true
	case reflect.Struct:
		if func() bool {
			nativeStep()
			return strings.HasPrefix(func() string {
				nativeStep()
				return func() reflect.Type { nativeStep(); return x.Type() }().
					Name()
			}(),

				"_Map[")
		}() {
			return func() bool { nativeStep(); return _equalMapHook(x, y) }()

		}
		for i := 0; i <
			func() int { nativeStep(); return x.NumField() }(); i++ {
			nativeStep()
			if !func() bool {
				nativeStep()
				return _equalValues(func() reflect.Value { nativeStep(); return x.Field(i) }(), func() reflect.Value { nativeStep(); return y.Field(i) }())
			}() {
				return false
			}
		}
		return true
	case reflect.Bool:
		return func() bool { nativeStep(); return x.Bool() }() == func() bool { nativeStep(); return y.Bool() }()

	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
		return func() int64 { nativeStep(); return x.Int() }() == func() int64 { nativeStep(); return y.Int() }()

	case reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64, reflect.Uintptr:
		return func() uint64 { nativeStep(); return x.Uint() }() == func() uint64 { nativeStep(); return y.Uint() }()

	case reflect.Float32, reflect.Float64:
		return func() float64 { nativeStep(); return x.Float() }() == func() float64 { nativeStep(); return y.Float() }()

	case reflect.String:
		return func() string { nativeStep(); return x.String() }() == func() string { nativeStep(); return y.String() }()

	}
	return false
}

// _equalMapHook compares maps, when the program has any.
var _equalMapHook func(x, y reflect.Value) bool

type _Rune int32

func (r _Rune) String() string {
	nativeEnter()
	defer nativeLeave(

	// _show renders a field value for String methods: strings are quoted,
	// everything else is printed as by _str.
	)
	return string(r)
}

func _show(x any) string {
	nativeEnter()
	defer nativeLeave()
	if v, ok := x.(interface{ _borkShow() string }); ok {
		return func() string { nativeStep(); return v._borkShow() }()

	}
	if s, ok := x.(string); ok {
		return func() string { nativeStep(); return strconv.Quote(s) }()

	}
	return func() string { nativeStep(); return _str(x) }()

}

func _str(x any) string {
	nativeEnter()
	defer nativeLeave()
	if v, ok := x.(interface{ _borkShow() string }); ok {
		return func() string { nativeStep(); return v._borkShow() }()

	}
	switch x := x.(type) {
	case float64:
		return func() string { nativeStep(); return _fmtFloat(x, 64) }()

	case float32:
		return func() string { nativeStep(); return _fmtFloat(float64(x), 32) }()

	case fmt.Stringer:
		return func() string { nativeStep(); return x.String() }()

	case string:
		return x
	}
	switch v := func() reflect.Value { nativeStep(); return reflect.ValueOf(x) }(); func() reflect.Kind { nativeStep(); return v.Kind() }() {
	case reflect.Struct:
		if func() string {
			nativeStep()
			return func() reflect.Type { nativeStep(); return v.Type() }().
				Name()
		}() ==
			"" &&
			func() int { nativeStep(); return v.NumField() }() >
				0 {
			parts := func() []string {
				nativeStep()
				return make([]string, func() int { nativeStep(); return v.NumField() }())
			}()

			for i := range parts {
				nativeStep()
				if func() reflect.StructField {
					nativeStep()
					return func() reflect.Type { nativeStep(); return v.Type() }().
						Field(i)
				}().
					Name != "E"+
					func() string { nativeStep(); return strconv.Itoa(i) }() {
					return func() string { nativeStep(); return fmt.Sprint(x) }()

				}
				parts[i] = func() string {
					nativeStep()
					return _show(func() any {
						nativeStep()
						return func() reflect.Value { nativeStep(); return v.Field(i) }().
							Interface()
					}(),
					)
				}()

			}
			text := func() string { nativeStep(); return strings.Join(parts, ", ") }()

			if func() int { nativeStep(); return len(parts) }() ==
				1 {
				text += ","
			}
			return "(" + text + ")"
		}
	case reflect.Slice:
		parts := func() []string {
			nativeStep()
			return make([]string, func() int { nativeStep(); return v.Len() }())
		}()

		for i := range parts {
			nativeStep()
			parts[i] = func() string {
				nativeStep()
				return _show(func() any {
					nativeStep()
					return func() reflect.Value { nativeStep(); return v.Index(i) }().
						Interface()
				}(),
				)
			}()

		}
		return "[" +
			func() string { nativeStep(); return strings.Join(parts, ", ") }() +
			"]"
	case reflect.Func:
		return "<function>"
	}
	return func() string { nativeStep(); return fmt.Sprint(x) }()

}

func _showList[T any](xs []T, show func(T) string) string {
	nativeEnter()
	defer nativeLeave()
	parts := func() []string {
		nativeStep()
		return make([]string, func() int { nativeStep(); return len(xs) }())
	}()

	for i, x := range xs {
		nativeStep()
		parts[i] = func() string { nativeStep(); return show(x) }()

	}
	return "[" +
		func() string { nativeStep(); return strings.Join(parts, ", ") }() +
		"]"
}

func _fmtFloat(f float64, bits int) string {
	nativeEnter()
	defer nativeLeave()
	if a := func() float64 { nativeStep(); return math.Abs(f) }(); func() bool { nativeStep(); return math.IsInf(f, 0) }() || func() bool { nativeStep(); return math.IsNaN(f) }() ||
		(a != 0 && (a < 1e-6 || a >= 1e21)) {
		return func() string { nativeStep(); return strconv.FormatFloat(f, 'g', -1, bits) }()

	}
	s := func() string { nativeStep(); return strconv.FormatFloat(f, 'f', -1, bits) }()

	if !func() bool { nativeStep(); return strings.Contains(s, ".") }() {
		s += ".0"
	}
	return s
}

// unsafe go functions

func _sql_scanStatement(statement _sql_Statement, dialect _sql_Dialect) any {
	nativeEnter()
	defer nativeLeave()
	type Dialect_Postgres = _sql_Dialect_Postgres
	type Dialect_Sqlite = _sql_Dialect_Sqlite
	type scanError = _sql_scanError
	type Error = _sql_Error
	type segment_text = _sql_segment_text
	type segment_bound = _sql_segment_bound
	type segment_name = _sql_segment_name
	type Rendered = _sql_Rendered

	postgres := false
	switch dialect.(type) {
	case Dialect_Postgres:
		postgres = true
	case Dialect_Sqlite:
	default:
		return scanError{detail: Error{operation: "interpolate", message: "unsupported SQL dialect"}, hole: -1}
	}
	var source _gopkg_strings.Builder
	holes := []any{}
	for _, part := range statement.segments {
		nativeStep()
		switch part := part.(type) {
		case segment_text:
			if func() bool { nativeStep(); return _gopkg_strings.ContainsRune(part.value, 0) }() {
				return scanError{detail: Error{operation: "interpolate", message: "SQL literal text contains NUL"}, hole: -1}
			}
			func(_callee func(s string) (int, error),

				_arg0 string) (int, error) {
				nativeStep()
				nativeAllocate(len(
					_arg0))
				return _callee(_arg0)
			}(source.WriteString, part.value)
		case segment_bound, segment_name:
			func(_callee func(c byte) error, _arg0 byte) error {
				nativeStep()
				nativeAllocate(1)
				return _callee(_arg0)
			}(source.WriteByte, 0)
			holes = func(_arg0 []any, _arg1 any) []any {
				nativeStep()
				nativeAllocate(64)
				return append(_arg0, _arg1)
			}(holes, part)
		default:
			panic("sql: invalid statement segment")
		}
	}
	text := func() string { nativeStep(); return source.String() }()

	var query _gopkg_strings.Builder
	params := []any{}
	hole := 0
	word := func(c byte) bool {
		nativeEnter()
		defer nativeLeave()
		return c >= 'a' && c <= 'z' || c >= 'A' && c <= 'Z' || c >= '0' && c <= '9' || c == '_' || c == '$' || c >= 128
	}
	fail := func(message string) scanError {
		nativeEnter()
		defer nativeLeave()
		return scanError{detail: Error{operation: "interpolate", message: message}, hole: -1}
	}
	failHole := func(message string) scanError {
		nativeEnter()
		defer nativeLeave()
		result := func() scanError { nativeStep(); return fail(message) }()

		result.hole = int64(hole)
		return result
	}
	failEnd := func(message string) scanError {
		nativeEnter()
		defer nativeLeave()
		result := func() scanError { nativeStep(); return fail(message) }()

		result.incomplete = true
		return result
	}
	// A zero byte represents a structural hole, never caller-supplied SQL bytes.
	for i := 0; i <
		func() int { nativeStep(); return len(text) }(); {
		nativeStep()
		c := text[i]
		if c == 0 {
			part := holes[hole]
			_, identifier := part.(segment_name)
			adjacent := func(j int) bool {
				nativeEnter()
				defer nativeLeave()
				if j < 0 || j >=
					func() int { nativeStep(); return len(text) }() {
					return false
				}
				c := text[j]
				if c == ':' {
					if postgres && (j == i+1 && j+1 <
						func() int { nativeStep(); return len(text) }() &&
						text[j+1] == ':' || j == i-1 && j > 0 && text[j-1] == ':') {
						return false
					}
					return true
				}
				return func() bool { nativeStep(); return word(c) }() ||
					c == 0 || c == '\'' || c == '"' || c == '`' || !postgres && (c == '[' || c == ']') || c == '@' || c == '.' && !identifier
			}
			if func() bool { nativeStep(); return adjacent(i - 1) }() || func() bool { nativeStep(); return adjacent(i + 1) }() {
				return func() scanError {
					nativeStep()
					return failHole(func(_callee func(format string, a ...any) string, _arg0 string, _arg1 int) string {
						nativeStep()
						nativeAllocate(52 + 32)
						return _callee(_arg0, _arg1)
					}(_gopkg_fmt.Sprintf, "SQL hole %d is inside or adjacent to a partial token", hole+1))
				}()

			}
			switch part := part.(type) {
			case segment_name:
				func(_callee func(c byte) error, _arg0 byte) error {
					nativeStep()
					nativeAllocate(1)
					return _callee(_arg0)
				}(query.WriteByte, '"')
				func(_callee func(s string) (int, error),

					_arg0 string) (int, error) {
					nativeStep()
					nativeAllocate(len(
						_arg0))
					return _callee(_arg0)
				}(query.WriteString, func(_callee func(s string, old string,
					new string) string, _arg0 string, _arg1 string, _arg2 string) string {
					nativeStep()
					nativeAllocate(nativeExpansion(len(_arg0), len(
						_arg2)))
					return _callee(_arg0, _arg1, _arg2)
				}(_gopkg_strings.ReplaceAll, part.value, "\"", "\"\""))
				func(_callee func(c byte) error, _arg0 byte) error {
					nativeStep()
					nativeAllocate(1)
					return _callee(_arg0)
				}(query.WriteByte, '"')
			case segment_bound:
				params = func(_arg0 []any, _arg1 any) []any {
					nativeStep()
					nativeAllocate(64)
					return append(_arg0, _arg1)
				}(params, part.value)
				if postgres {
					func(_callee func(c byte) error, _arg0 byte) error {
						nativeStep()
						nativeAllocate(1)
						return _callee(_arg0)
					}(query.WriteByte, '$')
					func(_callee func(s string) (int, error),

						_arg0 string) (int, error) {
						nativeStep()
						nativeAllocate(len(
							_arg0))
						return _callee(_arg0)
					}(query.WriteString, func() string {
						nativeStep()
						return _gopkg_strconv.Itoa(func() int { nativeStep(); return len(params) }())
					}())

				} else {
					func(_callee func(c byte) error, _arg0 byte) error {
						nativeStep()
						nativeAllocate(1)
						return _callee(_arg0)
					}(query.WriteByte, '?')
				}
			}
			hole++
			i++
			continue
		}
		start := i
		if c == '\'' || c == '"' || !postgres && (c == '`' || c == '[') {
			end := c
			if c == '[' {
				end = ']'
			}
			escape := postgres && c == '\'' && i > 0 && (text[i-1] == 'E' || text[i-1] == 'e') && (i < 2 || !func() bool { nativeStep(); return word(text[i-2]) }())
			i++
			closed := false
			for i <
				func() int { nativeStep(); return len(text) }() {
				nativeStep()
				if text[i] == 0 {
					return func() scanError { nativeStep(); return failHole("SQL hole is inside quoted text or an identifier") }()

				}
				if postgres && c == '\'' && text[i] == '\\' {
					if !escape {
						return func() scanError {
							nativeStep()
							return fail("Postgres ordinary strings with backslashes are ambiguous; use E-prefixed strings")
						}()

					}
					i++
					if i <
						func() int { nativeStep(); return len(text) }() &&
						text[i] == 0 {
						return func() scanError { nativeStep(); return failHole("SQL hole is inside an escape string") }()

					}
					if i <
						func() int { nativeStep(); return len(text) }() {
						i++
					}
					continue
				}
				if text[i] == end {
					i++
					if i <
						func() int { nativeStep(); return len(text) }() &&
						text[i] == end && c != '[' {
						i++
						continue
					}
					closed = true
					break
				}
				i++
			}
			if !closed {
				return func() scanError { nativeStep(); return failEnd("SQL quoted text is not terminated") }()

			}
		} else if c == '-' && i+1 <
			func() int { nativeStep(); return len(text) }() &&
			text[i+1] == '-' {
			i += 2
			for i <
				func() int { nativeStep(); return len(text) }() &&
				text[i] != '\n' && (!postgres || text[i] != '\r') {
				nativeStep()
				if text[i] == 0 {
					return func() scanError { nativeStep(); return failHole("SQL hole is inside a line comment") }()

				}
				i++
			}
		} else if c == '/' && i+1 <
			func() int { nativeStep(); return len(text) }() &&
			text[i+1] == '*' {
			i += 2
			depth := 1
			for i <
				func() int { nativeStep(); return len(text) }() &&
				depth > 0 {
				nativeStep()
				if text[i] == 0 {
					return func() scanError { nativeStep(); return failHole("SQL hole is inside a block comment") }()

				}
				if i+1 <
					func() int { nativeStep(); return len(text) }() &&
					text[i] == '*' && text[i+1] == '/' {
					depth--
					i += 2
				} else if postgres && i+1 <
					func() int { nativeStep(); return len(text) }() &&
					text[i] == '/' && text[i+1] == '*' {
					depth++
					i += 2
				} else {
					i++
				}
			}
			if depth > 0 {
				return func() scanError { nativeStep(); return failEnd("SQL block comment is not terminated") }()

			}
		} else if c >= 'a' && c <= 'z' || c >= 'A' && c <= 'Z' || c == '_' || c >= 128 {
			// Dollar signs inside unquoted identifiers are not parameters or quotes.
			i++
			for i <
				func() int { nativeStep(); return len(text) }() && func() bool { nativeStep(); return word(text[i]) }() {
				nativeStep()
				i++
			}
		} else if postgres && c == '$' {
			j := i + 1
			if j <
				func() int { nativeStep(); return len(text) }() &&
				text[j] >= '0' && text[j] <= '9' {
				return func() scanError {
					nativeStep()
					return fail("write a SQL value hole instead of a literal parameter placeholder")
				}()

			}
			for j <
				func() int { nativeStep(); return len(text) }() &&
				(text[j] >= 'a' && text[j] <= 'z' || text[j] >= 'A' && text[j] <= 'Z' || text[j] == '_' || text[j] >= 128 || j > i+1 && text[j] >= '0' && text[j] <= '9') {
				nativeStep()
				j++
			}
			if j <
				func() int { nativeStep(); return len(text) }() &&
				text[j] == '$' {
				delimiter := text[i : j+1]
				i = j + 1
				end := func() int { nativeStep(); return _gopkg_strings.Index(text[i:], delimiter) }()

				if end < 0 {
					if func() bool { nativeStep(); return _gopkg_strings.ContainsRune(text[i:], 0) }() {
						return func() scanError { nativeStep(); return failHole("SQL hole is inside a dollar quote") }()

					}
					return func() scanError { nativeStep(); return failEnd("Postgres dollar quote is not terminated") }()

				}
				if func() bool { nativeStep(); return _gopkg_strings.ContainsRune(text[i:i+end], 0) }() {
					return func() scanError { nativeStep(); return failHole("SQL hole is inside a dollar quote") }()

				}
				i += end +
					func() int { nativeStep(); return len(delimiter) }()

			} else {
				i++
			}
		} else if !postgres && (c == '?' || (c == ':' || c == '@' || c == '$') && i+1 <
			func() int { nativeStep(); return len(text) }() && func() bool { nativeStep(); return word(text[i+1]) }()) {
			return func() scanError {
				nativeStep()
				return fail("write a SQL value hole instead of a literal parameter placeholder")
			}()

		} else {
			i++
		}
		func(_callee func(s string) (int, error),

			_arg0 string) (int, error) {
			nativeStep()
			nativeAllocate(len(
				_arg0))
			return _callee(_arg0)
		}(query.WriteString, text[start:i])
	}
	return Rendered{query: func() string { nativeStep(); return query.String() }(), params: params}
}

func _sql_validateSQL(parts StaticParts, holes []InterpolationHole) []InterpolationIssue {
	nativeEnter()
	defer nativeLeave()
	type segment = _sql_segment
	type segment_text = _sql_segment_text
	type segment_name = _sql_segment_name
	type segment_bound = _sql_segment_bound
	type Statement = _sql_Statement
	scanStatement := _sql_scanStatement
	_ = scanStatement
	type Dialect_Sqlite = _sql_Dialect_Sqlite
	type scanError = _sql_scanError
	type Dialect_Postgres = _sql_Dialect_Postgres
	segments := []segment{segment_text{value: parts.values[0]}}
	for i, hole := range holes {
		nativeStep()
		identifier := false
		scalar := false
		unknown := false
		for _, kind := range hole.kinds {
			nativeStep()
			switch kind := kind.(type) {
			case InterpolationKind_Builtin:
				scalar = true
			case InterpolationKind_Named:
				if kind.packagePath == "bork/sql" && kind.name == "Identifier" {
					identifier = true
				} else if kind.packagePath == "bork/sql" && kind.name == "Null" {
					scalar = true
				} else {
					unknown = true
				}
			default:
				unknown = true
			}
		}
		if unknown || identifier && scalar {
			break
		}
		if identifier {
			segments = func(_arg0 []segment, _arg1 segment) []segment {
				nativeStep()
				nativeAllocate(64)
				return append(_arg0, _arg1)
			}(segments, segment_name{value: "_validation"})
		} else {
			segments = func(_arg0 []segment, _arg1 segment) []segment {
				nativeStep()
				nativeAllocate(64)
				return append(_arg0, _arg1)
			}(segments, segment_bound{value: int64(0)})
		}
		segments = func(_arg0 []segment, _arg1 segment) []segment {
			nativeStep()
			nativeAllocate(64)
			return append(_arg0, _arg1)
		}(segments, segment_text{value: parts.values[i+1]})
	}
	statement := Statement{segments: segments}
	sqlite, left := func() any { nativeStep(); return scanStatement(statement, Dialect_Sqlite{}) }().(scanError)
	postgres, right := func() any { nativeStep(); return scanStatement(statement, Dialect_Postgres{}) }().(scanError)
	if !left || !right || sqlite.incomplete || postgres.incomplete {
		return []InterpolationIssue{}
	}
	var hole Option[int64] = Option_None[int64]{}
	if sqlite.hole >= 0 && sqlite.hole == postgres.hole {
		hole = Option_Some[int64]{E0: sqlite.hole}
	}
	return []InterpolationIssue{{hole: hole, message: sqlite.detail.message}}
}
