// Package project scaffolds projects from the toolchain's bundled templates.
package project

import (
	"embed"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"strings"

	"golang.org/x/mod/module"
)

//go:embed templates/*/*.bork
var templates embed.FS

// New creates a project in a new directory. Existing paths are never replaced.
// An empty modulePath defaults to example.com/<directory name>.
func New(path, template, modulePath string) error {
	if template == "" {
		template = "default"
	}
	switch template {
	case "default", "cli", "http", "lib":
	default:
		return fmt.Errorf("unknown template %q (choose default, cli, http, or lib)", template)
	}
	path = filepath.Clean(path)
	name := filepath.Base(path)
	if name == "." || name == ".." || name == string(filepath.Separator) {
		return fmt.Errorf("choose a new project directory")
	}
	if modulePath == "" {
		modulePath = "example.com/" + name
	}
	if err := module.CheckPath(modulePath); err != nil {
		return fmt.Errorf("invalid module path: %w", err)
	}
	sources, err := fs.ReadDir(templates, "templates/"+template)
	if err != nil {
		return err
	}
	files := map[string]string{
		"bork.mod":   "module " + modulePath + "\n",
		".gitignore": "/" + name + "\n/" + name + ".exe\n",
		"README.md":  "# " + name + "\n\nCreated with `bork new --template " + template + "`. Requires bork and Go 1.26 or later.\n\n```sh\nbork check .\nbork test .\nbork fmt --check .\n",
	}
	if template != "lib" {
		files["README.md"] += "bork run .\n"
	}
	files["README.md"] += "```\n"
	if template == "cli" {
		files["README.md"] += "\nPass a name with `bork run . -- Ada`.\n"
	}
	if template == "http" {
		files["README.md"] += "\nRun the service, then try `curl http://localhost:8080/health`. Stop it with Ctrl-C.\n"
	}
	if template == "lib" {
		files["go.mod"] = "// Code generated by bork deps. DO NOT EDIT.\nmodule " + modulePath + "\n\ngo 1.26\n"
		files["bork.sum"] = ""
		files["README.md"] += "\nImport this package with `import \"" + modulePath + "\"`. Exported names start with a capital letter.\n"
	}
	for _, source := range sources {
		data, err := templates.ReadFile("templates/" + template + "/" + source.Name())
		if err != nil {
			return err
		}
		files[source.Name()] = string(data)
	}
	// Mkdir claims only the destination itself; a failed write can remove just
	// the directory we created, without touching pre-existing parent directories.
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	if err := os.Mkdir(path, 0o755); err != nil {
		return fmt.Errorf("create project: %w", err)
	}
	for name, data := range files {
		if err := os.WriteFile(filepath.Join(path, name), []byte(data), 0o644); err != nil {
			_ = os.RemoveAll(path)
			return err
		}
	}
	return nil
}

// NextSteps returns commands to run from the shell after creating a project.
func NextSteps(path, template string) string {
	// Single quotes protect spaces; ./ prevents cd from interpreting options.
	if !filepath.IsAbs(path) {
		path = "./" + path
	}
	quoted := "'" + strings.ReplaceAll(path, "'", "'\"'\"'") + "'"
	steps := "  cd " + quoted + "\n  bork check .\n  bork test .\n"
	if template != "lib" {
		steps += "  bork run .\n"
	}
	return steps
}
