package driver

import (
	"bytes"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/GiGurra/bork/internal/std"
	"golang.org/x/mod/modfile"
)

// Deps manages dependency manifests in the nearest bork module. Go runs in a
// temporary module so failed resolution cannot rewrite the user's manifests.
func Deps(path, action string, packages []string) error {
	switch action {
	case "init", "download", "migrate":
		if len(packages) != 0 {
			return fmt.Errorf("deps %s takes no package arguments", action)
		}
	case "get":
		if len(packages) == 0 {
			return errors.New("deps get needs at least one Go package or module")
		}
		for _, p := range packages {
			if strings.HasPrefix(p, "-") || strings.HasPrefix(p, ".") || strings.ContainsAny(p, "\\ \t\r\n") || p == "go" || p == "toolchain" || strings.HasPrefix(p, "go@") || strings.HasPrefix(p, "toolchain@") {
				return fmt.Errorf("invalid Go dependency query %q: use a package or module path, optionally followed by @version", p)
			}
		}
	default:
		return fmt.Errorf("unknown deps action %q", action)
	}
	mod, err := findModule(path)
	if err != nil {
		return err
	}
	if mod.path == "" {
		return errors.New("deps needs a bork.mod in the directory or a parent")
	}
	modPath := filepath.Join(mod.root, "go-deps.mod")
	sumPath := filepath.Join(mod.root, "go-deps.sum")
	data, err := os.ReadFile(modPath)
	if err != nil && !errors.Is(err, os.ErrNotExist) {
		return err
	}
	legacy := err == nil
	if legacy && len(mod.requirements) != 0 {
		if action == "migrate" {
			return finishDependencyMigration(mod, data)
		}
		return errors.New("legacy and bork.mod requirements cannot be mixed; remove one set before migration")
	}
	if action == "migrate" && !legacy {
		if _, err := os.Stat(filepath.Join(mod.root, "go-deps.sum")); err == nil {
			return finishDependencyMigration(mod, nil)
		}
		return errors.New("no legacy go-deps.mod to migrate")
	}
	native := !legacy || action == "migrate"
	var original []byte
	if native {
		original, err = os.ReadFile(filepath.Join(mod.root, ModFile))
		if err != nil {
			return err
		}
		parsed, err := parseModFile(string(original))
		if err != nil {
			return err
		}
		parsed.root = mod.root
		mod = parsed
		existing, readErr := os.ReadFile(filepath.Join(mod.root, "go.mod"))
		if readErr != nil && !errors.Is(readErr, os.ErrNotExist) {
			return readErr
		}
		if readErr == nil && !strings.HasPrefix(string(existing), generatedModuleHeader) {
			return errors.New("go.mod is not generated by bork deps; move it aside before generating the bork manifest")
		}
		if action == "init" && (readErr == nil || len(mod.requirements) != 0) {
			return errors.New("dependencies already initialized; use deps get or deps download")
		}
		if action == "init" {
			if _, err := os.Lstat(filepath.Join(mod.root, "bork.sum")); err == nil {
				return errors.New("bork.sum already exists; use deps get or deps download")
			} else if !errors.Is(err, os.ErrNotExist) {
				return err
			}
		}
		if !legacy {
			goVersion := ""
			if parsed, err := modfile.Parse("go.mod", existing, nil); err == nil && parsed.Go != nil {
				goVersion = parsed.Go.Version
			}
			data, err = dependencyModule(mod, goVersion)
			if err != nil {
				return err
			}
		}
		modPath = filepath.Join(mod.root, "go.mod")
		if !legacy {
			sumPath = filepath.Join(mod.root, "bork.sum")
		}
	} else if action == "init" {
		return errors.New("go-deps.mod already exists; use deps get or deps download (or deps migrate)")
	}
	if len(data) != 0 {
		manifest, err := modfile.Parse(modPath, data, nil)
		if err != nil {
			return err
		}
		if manifest.Toolchain != nil {
			return errors.New("go dependencies support only module, go, and pinned require declarations")
		}
	}
	dir, err := os.MkdirTemp("", "bork-deps-*")
	if err != nil {
		return err
	}
	defer func() { _ = os.RemoveAll(dir) }()
	run := func(args ...string) error {
		cmd := exec.Command("go", args...)
		cmd.Dir = dir
		cmd.Env = append(os.Environ(), "GOWORK=off", "GO111MODULE=on", "GOFLAGS=")
		if out, err := cmd.CombinedOutput(); err != nil {
			return fmt.Errorf("go %s: %w\n%s", strings.Join(args, " "), err, strings.TrimSpace(string(out)))
		}
		return nil
	}
	if len(data) == 0 {
		if err := run("mod", "init", mod.path); err != nil {
			return err
		}
	} else if err := os.WriteFile(filepath.Join(dir, "go.mod"), data, 0o644); err != nil {
		return err
	}
	sums, err := os.ReadFile(sumPath)
	if err != nil && !errors.Is(err, os.ErrNotExist) {
		return err
	}
	if err := os.WriteFile(filepath.Join(dir, "go.sum"), sums, 0o644); err != nil {
		return err
	}
	if action == "get" {
		if err := run(append([]string{"get"}, packages...)...); err != nil {
			return err
		}
	}
	if action != "init" {
		// Download every requirement, including indirect ones, to pin both the
		// module and go.mod hashes required by check and build.
		if err := run("mod", "download", "all"); err != nil {
			return err
		}
	}
	data, err = os.ReadFile(filepath.Join(dir, "go.mod"))
	if err != nil {
		return err
	}
	manifest, err := modfile.Parse(modPath, data, nil)
	if err != nil {
		return err
	}
	// Go may add a toolchain suggestion when upgrading dependencies. Generated
	// programs use the go directive instead, so do not persist that suggestion.
	manifest.DropToolchainStmt()
	data, err = manifest.Format()
	if err != nil {
		return err
	}
	sums, err = os.ReadFile(filepath.Join(dir, "go.sum"))
	if err != nil {
		return err
	}
	if _, _, err := std.GoModuleFiles(nil, std.GoDependencyManifest{Name: mod.root, Mod: data, Sum: sums}); err != nil {
		return fmt.Errorf("go dependencies: %w", err)
	}
	outputs := []struct {
		path string
		data []byte
	}{{sumPath, sums}, {modPath, data}}
	if native {
		updated := updateModuleRequirements(original, manifest.Require)
		updatedMod, err := parseModFile(string(updated))
		if err != nil {
			return err
		}
		goVersion := ""
		if manifest.Go != nil {
			goVersion = manifest.Go.Version
		}
		generated, err := generatedModule(updatedMod, goVersion)
		if err != nil {
			return err
		}
		outputs = []struct {
			path string
			data []byte
		}{{filepath.Join(mod.root, "bork.sum"), sums}, {modPath, generated}, {filepath.Join(mod.root, ModFile), updated}}
	}
	var staged []string
	defer func() {
		for _, path := range staged {
			_ = os.Remove(path)
		}
	}()
	for _, output := range outputs {
		path, err := stageGoManifest(output.path, output.data)
		if err != nil {
			return err
		}
		staged = append(staged, path)
	}
	// Publish checksums first. Interrupted manifest publication is diagnosed
	// as drift and can be repaired from bork.mod with deps download.
	if native {
		current, err := os.ReadFile(filepath.Join(mod.root, ModFile))
		if err != nil {
			return err
		}
		if !bytes.Equal(current, original) {
			return errors.New("bork.mod changed during dependency resolution; retry the command")
		}
	}
	for i, output := range outputs {
		if err := os.Rename(staged[i], output.path); err != nil {
			return err
		}
	}
	if action == "migrate" {
		return removeLegacyDependencies(mod.root)
	}
	return nil
}

// A successful native publication can precede an interrupted legacy cleanup.
// Resume only when both sets agree, never by dropping conflicting requirements.
func finishDependencyMigration(mod module, legacy []byte) error {
	data, err := os.ReadFile(filepath.Join(mod.root, "go.mod"))
	if err != nil {
		return err
	}
	if err := checkGeneratedModule(mod, data); err != nil {
		return err
	}
	if len(legacy) != 0 {
		f, err := modfile.Parse("go-deps.mod", legacy, nil)
		if err != nil {
			return err
		}
		if len(f.Require) != len(mod.requirements) {
			return errors.New("legacy and bork.mod requirements differ; reconcile them before migration")
		}
		versions := map[string]string{}
		for _, dep := range mod.requirements {
			versions[dep.Path] = dep.Version
		}
		for _, dep := range f.Require {
			if versions[dep.Mod.Path] != dep.Mod.Version {
				return errors.New("legacy and bork.mod requirements differ; reconcile them before migration")
			}
			delete(versions, dep.Mod.Path)
		}
		if len(versions) != 0 {
			return errors.New("legacy and bork.mod requirements differ; reconcile them before migration")
		}
	}
	sums, err := os.ReadFile(filepath.Join(mod.root, "bork.sum"))
	if err != nil {
		return err
	}
	if _, _, err := std.GoModuleFiles(nil, std.GoDependencyManifest{Name: mod.root, Mod: data, Sum: sums}); err != nil {
		return err
	}
	if len(legacy) != 0 {
		if _, _, err := std.GoModuleFiles(nil, std.GoDependencyManifest{Name: mod.root, Mod: legacy, Sum: sums}); err != nil {
			return err
		}
	}
	return removeLegacyDependencies(mod.root)
}

func removeLegacyDependencies(root string) error {
	for _, name := range []string{"go-deps.mod", "go-deps.sum"} {
		if err := os.Remove(filepath.Join(root, name)); err != nil && !errors.Is(err, os.ErrNotExist) {
			return err
		}
	}
	return nil
}

func stageGoManifest(path string, data []byte) (string, error) {
	mode := os.FileMode(0o644)
	if st, err := os.Stat(path); err == nil {
		mode = st.Mode().Perm()
	} else if !errors.Is(err, os.ErrNotExist) {
		return "", err
	}
	f, err := os.CreateTemp(filepath.Dir(path), ".bork-deps-*")
	if err != nil {
		return "", err
	}
	name := f.Name()
	if _, err = f.Write(data); err == nil {
		err = f.Chmod(mode)
	}
	if closeErr := f.Close(); err == nil {
		err = closeErr
	}
	if err != nil {
		_ = os.Remove(name)
		return "", err
	}
	return name, nil
}
