package driver

import (
	"bytes"
	"crypto/sha256"
	"errors"
	"io"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"text/scanner"
	"unicode"
)

const goExecutionAssemblyLimit = 8 << 20
const goExecutionAssemblyTotalLimit = 16 << 20

// Go 1.26/1.27's assembler resolves includes against the package working
// directory, generated object directory, then GOROOT/pkg/include. go_asm.h is
// generated by the pinned compiler from the selected Go files; all other
// includes require positive content and earlier negative search evidence.
func (c *goExecutionCapture) assemblyIncludes(pkg goExecutionPackage, root string) error {
	visited := map[string]bool{}

	var visit func(string, int) error
	visit = func(path string, depth int) error {
		if depth > 256 {
			return errors.New("go assembly include depth exceeded")
		}
		if visited[path] {
			return nil
		}
		visited[path] = true
		if err := c.file(path); err != nil {
			return err
		}
		file, err := openGoExecutionFile(path)
		if err != nil {
			return err
		}
		info, statErr := file.Stat()
		if statErr != nil || !info.Mode().IsRegular() {
			_ = file.Close()
			return errors.New("unsupported go assembly input type")
		}
		data, err := io.ReadAll(io.LimitReader(file, goExecutionAssemblyLimit+1))
		closeErr := file.Close()
		if err != nil {
			return err
		}
		if closeErr != nil {
			return closeErr
		}
		if len(data) > goExecutionAssemblyLimit || int64(len(data)) > c.assemblyRemaining {
			return errors.New("go assembly include budget exceeded")
		}
		c.assemblyRemaining -= int64(len(data))
		digest := sha256.Sum256(data)
		if digest != c.digests[path] {
			return errors.New("go assembly input changed during capture")
		}

		names, err := c.assemblyIncludeNames(data)
		if err != nil {
			return err
		}
		for _, name := range names {

			candidate := filepath.Join(pkg.Dir, name)
			if err := c.includeSearch(filepath.Dir(candidate), pkg.Dir); err != nil {
				return err
			}
			info, err := os.Stat(candidate)
			if err == nil {
				if !info.Mode().IsRegular() {
					return errors.New("unsupported go assembly include type")
				}
			} else if errors.Is(err, os.ErrNotExist) {
				if name == "go_asm.h" {
					continue
				}
				candidate = filepath.Join(root, "pkg", "include", name)
				if err := c.includeSearch(filepath.Dir(candidate), filepath.Join(root, "pkg", "include")); err != nil {
					return err
				}
				if _, err := os.Stat(candidate); err != nil {
					return errors.New("unresolved go assembly include")
				}
			} else {
				return err
			}
			resolved, err := filepath.EvalSymlinks(candidate)
			resolvedRoot, rootErr := filepath.EvalSymlinks(root)
			if err != nil || rootErr != nil || !withinGoExecutionRoot(resolved, resolvedRoot) {
				return errors.New("go assembly include outside selected SDK")
			}
			if err := visit(candidate, depth+1); err != nil {
				return err
			}
		}
		return nil
	}
	for _, name := range pkg.SFiles {
		if err := visit(filepath.Join(pkg.Dir, name), 0); err != nil {
			return err
		}
	}
	return nil
}

// includeSearch captures the existing prefix, including membership at the first
// absent component. A previously missing higher-priority include then invalidates.
func (c *goExecutionCapture) includeSearch(path, root string) error {
	if !withinGoExecutionRoot(path, root) {
		return errors.New("go assembly search outside root")
	}
	rel, err := filepath.Rel(root, path)
	if err != nil {
		return err
	}
	current := root
	if _, err := c.directory(current); err != nil {
		return err
	}
	if rel == "." {
		return nil
	}
	for _, component := range strings.Split(rel, string(filepath.Separator)) {
		current = filepath.Join(current, component)
		info, err := os.Stat(current)
		if errors.Is(err, os.ErrNotExist) {
			return nil
		}
		if err != nil {
			return err
		}
		if !info.IsDir() {
			return errors.New("unsupported go assembly search component")
		}
		if _, err := c.directory(current); err != nil {
			return err
		}
	}
	return nil
}

// Match the supported assembler's lexical comment handling. Directives cannot
// be recognized by line prefixes: #/**/include and include/**/ are valid tokens.
func (c *goExecutionCapture) assemblyIncludeNames(data []byte) ([]string, error) {
	var lexer scanner.Scanner
	lexer.Init(bytes.NewReader(data))
	lexer.Whitespace = 1<<'\t' | 1<<'\r' | 1<<' '
	lexer.Mode = scanner.ScanChars | scanner.ScanFloats | scanner.ScanIdents | scanner.ScanInts | scanner.ScanStrings | scanner.ScanComments | scanner.SkipComments
	lexer.IsIdentRune = func(ch rune, index int) bool {
		return unicode.IsLetter(ch) || ch == '_' || ch == '·' || ch == '∕' || index > 0 && unicode.IsDigit(ch)
	}
	var failure error
	lexer.Error = func(*scanner.Scanner, string) { failure = errors.New("unsupported go assembly lexical syntax") }
	next := func() rune {
		c.includeSteps++
		if c.includeSteps > 1000000 {
			failure = errors.New("go assembly parsing operation budget exceeded")
			return scanner.EOF
		}
		return lexer.Scan()
	}
	var names []string
	for token := next(); token != scanner.EOF; token = next() {
		if failure != nil {
			return nil, failure
		}
		if token != '#' {
			continue
		}
		if next() != scanner.Ident {
			return nil, errors.New("unsupported go assembly directive")
		}
		switch lexer.TokenText() {
		case "include":
			if next() != scanner.String {
				return nil, errors.New("unsupported go assembly include operand")
			}
			name, err := strconv.Unquote(lexer.TokenText())
			if err != nil || !validGoExecutionRelative(name) {
				return nil, errors.New("unsupported go assembly include")
			}
			if len(names) >= goExecutionEntryLimit {
				return nil, errors.New("go assembly include count budget exceeded")
			}
			names = append(names, name)
		case "define", "undef", "ifdef", "ifndef", "else", "endif", "line":
			// Continue lexing macro bodies as well; possible includes are conservative.
		default:
			return nil, errors.New("unsupported go assembly directive")
		}
	}
	if failure != nil {
		return nil, failure
	}
	return names, nil
}
