package driver

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/GiGurra/bork/internal/std"
	"golang.org/x/mod/modfile"
	gomodule "golang.org/x/mod/module"
	"golang.org/x/mod/semver"
)

const generatedModuleHeader = "// Code generated by bork deps. DO NOT EDIT.\n"
const dependencyGoVersion = "1.26"

func dependencyModule(mod module, goVersion string) ([]byte, error) {
	f := &modfile.File{}
	if err := f.AddModuleStmt(mod.path); err != nil {
		return nil, err
	}
	if goVersion == "" || semver.Compare("v"+goVersion, "v"+dependencyGoVersion) < 0 {
		goVersion = dependencyGoVersion
	}
	if err := f.AddGoStmt(goVersion); err != nil {
		return nil, err
	}
	deps := append([]gomodule.Version(nil), mod.requirements...)
	sort.Slice(deps, func(i, j int) bool { return deps[i].Path < deps[j].Path })
	for _, dep := range deps {
		if err := f.AddRequire(dep.Path, dep.Version); err != nil {
			return nil, err
		}
	}
	return f.Format()
}

func generatedModule(mod module, goVersion string) ([]byte, error) {
	data, err := dependencyModule(mod, goVersion)
	if err != nil {
		return nil, err
	}
	return append([]byte(generatedModuleHeader), data...), nil
}

func checkGeneratedModule(mod module, data []byte) error {
	drift := func() error {
		return fmt.Errorf("%s: generated Go manifest differs from bork.mod; run bork deps download", filepath.Join(mod.root, "go.mod"))
	}
	if !strings.HasPrefix(string(data), generatedModuleHeader) {
		return drift()
	}
	f, err := modfile.Parse("go.mod", data, nil)
	if err != nil || f.Module == nil || f.Module.Mod.Path != mod.path || f.Go == nil || len(f.Require) != len(mod.requirements) {
		return drift()
	}
	if len(f.Replace) != 0 || len(f.Exclude) != 0 || len(f.Retract) != 0 || f.Toolchain != nil || len(f.Godebug) != 0 || len(f.Tool) != 0 || len(f.Ignore) != 0 {
		return drift()
	}
	requirements := map[string]string{}
	for _, dep := range mod.requirements {
		requirements[dep.Path] = dep.Version
	}
	for _, dep := range f.Require {
		if requirements[dep.Mod.Path] != dep.Mod.Version {
			return drift()
		}
		delete(requirements, dep.Mod.Path)
	}
	if len(requirements) != 0 || semver.Compare("v"+f.Go.Version, "v"+dependencyGoVersion) < 0 {
		return drift()
	}
	return nil
}

func moduleDependencies(mod module, reader sourceReader) ([]std.GoDependencyManifest, error) {
	legacyPath := filepath.Join(mod.root, "go-deps.mod")
	legacy, err := reader.readFile(legacyPath)
	if err != nil && !errors.Is(err, os.ErrNotExist) {
		return nil, err
	}
	goPath := filepath.Join(mod.root, "go.mod")
	data, goErr := reader.readFile(goPath)
	if goErr != nil && !errors.Is(goErr, os.ErrNotExist) {
		return nil, goErr
	}
	generated := strings.HasPrefix(string(data), generatedModuleHeader)
	if err == nil {
		if len(mod.requirements) != 0 || generated {
			return nil, fmt.Errorf("%s: legacy and bork.mod requirements cannot be mixed; run bork deps migrate", mod.root)
		}
		sumPath := filepath.Join(mod.root, "go-deps.sum")
		sum, err := reader.readFile(sumPath)
		if err != nil {
			return nil, fmt.Errorf("%s: read pinned Go checksums: %w", sumPath, err)
		}
		return []std.GoDependencyManifest{{Name: mod.root, Mod: legacy, Sum: sum}}, nil
	}
	sumPath := filepath.Join(mod.root, "bork.sum")
	sum, sumErr := reader.readFile(sumPath)
	if sumErr != nil && !errors.Is(sumErr, os.ErrNotExist) {
		return nil, sumErr
	}
	if len(mod.requirements) == 0 && !generated && errors.Is(sumErr, os.ErrNotExist) {
		return nil, nil
	}
	if goErr != nil || checkGeneratedModule(mod, data) != nil {
		return nil, fmt.Errorf("%s: generated Go manifest differs from bork.mod; run bork deps download", goPath)
	}
	if sumErr != nil && len(mod.requirements) != 0 {
		return nil, fmt.Errorf("%s: missing pinned checksums; run bork deps download", sumPath)
	}
	return []std.GoDependencyManifest{{Name: mod.root, Mod: data, Sum: sum}}, nil
}

// Preserve comments and unsafe grants when the helper updates requirements.
func updateModuleRequirements(data []byte, requirements []*modfile.Require) []byte {
	versions := map[string]string{}
	for _, dep := range requirements {
		versions[dep.Mod.Path] = dep.Mod.Version
	}
	var lines []string
	for _, line := range strings.Split(strings.TrimRight(string(data), "\n"), "\n") {
		declaration, comment, hasComment := strings.Cut(line, "//")
		fields := strings.Fields(declaration)
		if len(fields) != 0 && fields[0] == "require" {
			if version, exists := versions[fields[1]]; exists {
				line = "require " + fields[1] + " " + version
				if hasComment {
					line += " //" + comment
				}
				lines = append(lines, line)
				delete(versions, fields[1])
			} else if hasComment {
				lines = append(lines, "//"+comment)
			}
			continue
		}
		lines = append(lines, line)
	}
	paths := make([]string, 0, len(versions))
	for path := range versions {
		paths = append(paths, path)
	}
	sort.Strings(paths)
	for _, path := range paths {
		lines = append(lines, "require "+path+" "+versions[path])
	}
	return []byte(strings.Join(lines, "\n") + "\n")
}
