[language-server.bork]
command = "bork"
args = ["lsp"]

[[language]]
name = "bork"
scope = "source.bork"
file-types = ["bork"]
shebangs = ["bork"]
roots = ["bork.mod"]
comment-token = "//"
block-comment-tokens = { start = "/*", end = "*/" }
language-servers = ["bork"]
auto-format = true
indent = { tab-width = 2, unit = "  " }

[[grammar]]
name = "bork"
source = { git = "https://github.com/GiGurra/bork", rev = "a2bfee77cf7e8f66373f6b1a688a4ae2e633bdc5", subpath = "editors/tree-sitter-bork" }
